# BioSeqDownloader API Usage Demo
This document demonstrates how to use the BioSeqDownloader API implementations programmatically.

### Importing the API
To use the BioSeqDownloader API, you first need to import the necessary classes from the `BioSeqDownloader` package.

Every API implementation is located in its own module inside the `bioseq_dl` package. For every database available, there is a corresponding interface class that provides methods to interact with that database. We use the `{database_name}Interface` naming convention for these classes.

In [1]:
from bioseq_dl import AlphafoldInterface

### Instantiating the API
Different API have different requirements for instantiation. Some may require an email address, while others may need an API key or token. Please refer to the specific database documentation for details on how to instantiate the API correctly.

In [2]:
instance = AlphafoldInterface(
    structures=["pdb"],
)

### Making a Request
Once you have instantiated the API, you can use its methods to make requests to the database. Every API class provides 2 main methods for making requests:
- `fetch_single`: This method is used to fetch data for a single identifier.
- `fetch_batch`: This method is used to fetch data for multiple identifiers in a batch.

In some databases `fetch_single` can be used to fetch data for multiple identifiers as well.

Every database has their own query definition and accepted parameters. Please refer to the specific database documentation for details on how to construct your queries.
Some common parameters include:
- `query`: The identifier or list of identifiers to search for.
- `method`: It refers to a endpoint or a specific type of search.
- `parse`: A boolean indicating whether to parse the response into a structured format. By default it will use the configuration defined at instantiation. You can use your own fields by giving fields_to_extract parameter.
- `format`: The desired format of the output data. It can be "json", "list", "dict", or "dataframe".

This will return 2 objects: the fetched data and metadata about the request. The fetched data can be a list, dictionary, or pandas DataFrame depending on the parameters used. The metadata contains additional information about the request, such as cached IDs.

In [3]:
response, metadata = instance.fetch_single(
    query="P02666",
    method="prediction",
    parse=True,
    format="dataframe",
)

2026-01-11 22:40:16 | INFO     | bioseq_dl.interfaces.alphafold | Downloading structure AF-P02666-F1-model_v6.pdb...

In [5]:
response

,entry,gene,tax_id,organism,is_reviewed,is_reference,pdbUrl
0,AF-P02666-F1,CSN2,9913,Bos taurus,True,True,https://alphafold.ebi.ac.uk/files/AF-P02666-F1...

In [4]:
metadata

{'cached_ids': ['P02666'],
 'cached_subqueries': ['P02666'],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 1,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'entry', 'dtype': 'object', 'n_missing': 0},
   {'name': 'gene', 'dtype': 'object', 'n_missing': 0},
   {'name': 'tax_id', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism', 'dtype': 'object', 'n_missing': 0},
   {'name': 'is_reviewed', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'is_reference', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'pdbUrl', 'dtype': 'object', 'n_missing': 0}]},
 'execution_time': 0.003799915313720703,
 'api_name': 'Alphafold',
 'method': 'prediction',
 'option': None}

In [6]:
response, metadata = instance.fetch_batch(
    queries=["P02666", "Q9TSI0", "P33048", "P11839", "O15552", "P76011"],
    method="prediction",
    parse=False,
    format="dataframe",
)

In [7]:
response.head(2)

,toolUsed,providerId,entityType,isUniProt,modelEntityId,modelCreatedDate,sequenceVersionDate,globalMetricValue,fractionPlddtVeryLow,fractionPlddtLow,...,paeImageUrl,msaUrl,plddtDocUrl,paeDocUrl,entryId,uniprotSequence,uniprotStart,uniprotEnd,isReferenceProteome,isReviewed
0,AlphaFold Monomer v2.0 pipeline,GDM,protein,True,AF-P02666-F1,2025-08-01T00:00:00Z,1989-07-01T00:00:00Z,60.84,0.129,0.719,...,https://alphafold.ebi.ac.uk/files/AF-P02666-F1...,https://alphafold.ebi.ac.uk/files/msa/AF-P0266...,https://alphafold.ebi.ac.uk/files/AF-P02666-F1...,https://alphafold.ebi.ac.uk/files/AF-P02666-F1...,AF-P02666-F1,MKVLILACLVALALARELEELNVPGEIVESLSSSEESITRINKKIE...,1,224,True,True
1,AlphaFold Monomer v2.0 pipeline,GDM,protein,True,AF-Q9TSI0-F1,2025-08-01T00:00:00Z,2000-05-01T00:00:00Z,61.66,0.183,0.589,...,https://alphafold.ebi.ac.uk/files/AF-Q9TSI0-F1...,https://alphafold.ebi.ac.uk/files/msa/AF-Q9TSI...,https://alphafold.ebi.ac.uk/files/AF-Q9TSI0-F1...,https://alphafold.ebi.ac.uk/files/AF-Q9TSI0-F1...,AF-Q9TSI0-F1,MKVLILACLVALALARELEELNVPGEIVESLSSSEESITHINKKIE...,1,224,False,True

In [8]:
metadata

{'cached_ids': ['P02666_prediction',
  'Q9TSI0_prediction',
  'P33048_prediction',
  'P11839_prediction',
  'O15552_prediction',
  'P76011_prediction'],
 'cached_subqueries': ['P02666',
  'Q9TSI0',
  'P33048',
  'P11839',
  'O15552',
  'P76011'],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 6,
 'data_info': {'total_entries': 6,
  'data_type': 'DataFrame',
  'columns': [{'name': 'toolUsed', 'dtype': 'object', 'n_missing': 0},
   {'name': 'providerId', 'dtype': 'object', 'n_missing': 0},
   {'name': 'entityType', 'dtype': 'object', 'n_missing': 0},
   {'name': 'isUniProt', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'modelEntityId', 'dtype': 'object', 'n_missing': 0},
   {'name': 'modelCreatedDate', 'dtype': 'object', 'n_missing': 0},
   {'name': 'sequenceVersionDate', 'dtype': 'object', 'n_missing': 0},
   {'name': 'globalMetricValue', 'dtype': 'float64', 'n_missing': 0},
   {'name': 'fractionPlddtVeryLow', 'dtype': 'float64', 'n_missing': 0},
   {'name': 'fractionPlddtLow', 'dtype': 'float64', 'n_missing': 0},
   {'name': 'fractionPlddtConfident', 'dtype': 'float64', 'n_missing': 0},
   {'name': 'fractionPlddtVeryHigh', 'dtype': 'float64', 'n_missing': 0},
   {'name': 'latestVersion', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'allVersions', 'dtype': 'object', 'n_missing': 0},
   {'name': 'sequence', 'dtype': 'object', 'n_missing': 0},
   {'name': 'sequenceStart', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'sequenceEnd', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'sequenceChecksum', 'dtype': 'object', 'n_missing': 0},
   {'name': 'isUniProtReviewed', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'gene', 'dtype': 'object', 'n_missing': 0},
   {'name': 'uniprotAccession', 'dtype': 'object', 'n_missing': 0},
   {'name': 'uniprotId', 'dtype': 'object', 'n_missing': 0},
   {'name': 'uniprotDescription', 'dtype': 'object', 'n_missing': 0},
   {'name': 'taxId', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organismScientificName', 'dtype': 'object', 'n_missing': 0},
   {'name': 'isUniProtReferenceProteome', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'bcifUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'cifUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'pdbUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'paeImageUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'msaUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'plddtDocUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'paeDocUrl', 'dtype': 'object', 'n_missing': 0},
   {'name': 'entryId', 'dtype': 'object', 'n_missing': 0},
   {'name': 'uniprotSequence', 'dtype': 'object', 'n_missing': 0},
   {'name': 'uniprotStart', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'uniprotEnd', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'isReferenceProteome', 'dtype': 'bool', 'n_missing': 0},
   {'name': 'isReviewed', 'dtype': 'bool', 'n_missing': 0}]},
 'execution_time': 2.5987625122070312e-05,
 'api_name': '',
 'method': 'prediction',
 'option': None,
 'source_api': 'Alphafold'}

# Other API examples

## BioDBNet

### Importing the API

In [9]:
from bioseq_dl import BioDBNetInterface

### Instantiating the API

In [10]:
instance = BioDBNetInterface()

### Making a request

In [11]:
response, metadata = instance.fetch_single(
    query={
        "input": "genesymbol",
        "inputValues": ["APP", "SLC9A9"],
        "outputs": "taxonid,genesymbol,affyid,go-biologicalprocess",
        "taxonId": "9606",
    },
    method="db2db",
    parse=True,
    format="dataframe",
)

In [12]:
response.dropna(axis=1, how="all")

,affy_id,gene_symbol,go_biological_process,taxon_id
0,"[11738008_s_at [Chip: PrimeView], 11746866_a_a...",APP,[GO:0006357 [Name: regulation of transcription...,9606 [Organism: human] [Scientific Name: Homo ...
1,"[227791_at [Chip: U133_Plus_2], 43140_at [Chip...",SLC9A9,[GO:0042742 [Name: defense response to bacteri...,9606 [Organism: human] [Scientific Name: Homo ...
2,"[11738008_s_at [Chip: PrimeView], 11746866_a_a...",APP,[GO:0006357 [Name: regulation of transcription...,9606 [Organism: human] [Scientific Name: Homo ...
3,"[227791_at [Chip: U133_Plus_2], 43140_at [Chip...",SLC9A9,[GO:0042742 [Name: defense response to bacteri...,9606 [Organism: human] [Scientific Name: Homo ...

In [13]:
metadata

{'cached_ids': ['APP_genesymbol_taxonid,genesymbol,affyid,go-biologicalprocess_9606',
  'SLC9A9_genesymbol_taxonid,genesymbol,affyid,go-biologicalprocess_9606'],
 'cached_subqueries': [{'input': 'genesymbol',
   'inputValues': 'APP',
   'outputs': 'taxonid,genesymbol,affyid,go-biologicalprocess',
   'taxonId': '9606'},
  {'input': 'genesymbol',
   'inputValues': 'SLC9A9',
   'outputs': 'taxonid,genesymbol,affyid,go-biologicalprocess',
   'taxonId': '9606'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 4,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'affy_id', 'dtype': 'object', 'n_missing': 0},
   {'name': 'agilent_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'allergome_code', 'dtype': 'object', 'n_missing': 4},
   {'name': 'apidb_cryptodb_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'biocarta_pathway_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'biocyc_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ccds_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'chromosomal_location', 'dtype': 'object', 'n_missing': 4},
   {'name': 'cleanex_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'codelink_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'cosmic_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'cpdb_protein_interactor', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ctd_disease_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ctd_disease_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'cygd_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'dbsnp_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'dictybase_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'dip_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'disprot_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'drugbank_drug_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'drugbank_drug_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'drugbank_drug_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ec_number', 'dtype': 'object', 'n_missing': 4},
   {'name': 'echobase_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ecogene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ensembl_biotype', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ensembl_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ensembl_gene_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ensembl_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ensembl_transcript_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'flybase_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'flybase_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'flybase_transcript_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gad_disease_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gad_disease_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'genbank_nucleotide_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'genbank_nucleotide_gi', 'dtype': 'object', 'n_missing': 4},
   {'name': 'genbank_protein_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'genbank_protein_gi', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_symbol', 'dtype': 'object', 'n_missing': 0},
   {'name': 'gene_symbol_and_synonyms', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_symbol_ordered_locus', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_symbol_orf', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gene_synonyms', 'dtype': 'object', 'n_missing': 4},
   {'name': 'genefarm_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'go_biological_process', 'dtype': 'object', 'n_missing': 0},
   {'name': 'go_cellular_component', 'dtype': 'object', 'n_missing': 4},
   {'name': 'go_molecular_function', 'dtype': 'object', 'n_missing': 4},
   {'name': 'go_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'gsea_standard_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'h_inv_locus_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hamap_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hgnc_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hmdb_metabolite', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_all_ens_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_all_ens_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_all_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_human_ens_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_human_ens_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_human_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_mouse_ens_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_mouse_ens_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_mouse_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_rat_ens_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_rat_ens_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homolog_rat_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'homologene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hpa_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hprd_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hprd_protein_complex', 'dtype': 'object', 'n_missing': 4},
   {'name': 'hprd_protein_interactor', 'dtype': 'object', 'n_missing': 4},
   {'name': 'illumina_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'imgt_gene_db_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'interpro_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ipi_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_disease_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_orthology_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_pathway_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_pathway_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'kegg_pathway_title', 'dtype': 'object', 'n_missing': 4},
   {'name': 'legiolist_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'leproma_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'locus_tag', 'dtype': 'object', 'n_missing': 4},
   {'name': 'maizegdb_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'merops_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mgc_zgc_xgc_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mgc_zgc_xgc_image_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mgc_zgc_xgc_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mgi_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mim_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mim_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'mirbase_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ncipid_pathway_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ncipid_protein_complex', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ncipid_protein_interactor', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ncipid_ptm', 'dtype': 'object', 'n_missing': 4},
   {'name': 'orphanet_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'panther_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'paralog_ens_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pbr_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pdb_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'peroxibase_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pfam_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pharmgkb_drug_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pharmgkb_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pir_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pirsf_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pptasedb_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'prints_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'prodom_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'prosite_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pseudocap_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'pubmed_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'reactome_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'reactome_pathway_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'rebase_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_genomic_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_genomic_gi', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_mrna_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_ncrna_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_nucleotide_gi', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_protein_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'refseq_protein_gi', 'dtype': 'object', 'n_missing': 4},
   {'name': 'rfam_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'rgd_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'sgd_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'smart_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'string_protein_interactor', 'dtype': 'object', 'n_missing': 4},
   {'name': 'tair_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'taxon_id', 'dtype': 'object', 'n_missing': 0},
   {'name': 'tcdb_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'tigrfams_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'tuberculist_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'ucsc_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'unigene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'uniprot_accession', 'dtype': 'object', 'n_missing': 4},
   {'name': 'uniprot_entry_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'uniprot_info', 'dtype': 'object', 'n_missing': 4},
   {'name': 'uniprot_protein_name', 'dtype': 'object', 'n_missing': 4},
   {'name': 'unists_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'vectorbase_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'vega_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'vega_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'vega_transcript_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'wormbase_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'wormpep_protein_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'xenbase_gene_id', 'dtype': 'object', 'n_missing': 4},
   {'name': 'zfin_id', 'dtype': 'object', 'n_missing': 4}]},
 'execution_time': 0.029016733169555664,
 'api_name': 'BioDBNet',
 'method': 'db2db',
 'option': None}

In [14]:
response, metadata = instance.fetch_single(
    query={"pathways": "1", "taxonId": "9606"},
    method="getpathways",
    parse=True,
    format="dataframe",
)

In [15]:
response

,name,title,description,source_database
0,NS1 Mediated Effects on Host Pathways,NS1 Mediated Effects on Host Pathways,NS1 Mediated Effects on Host Pathways,REACTOME
1,2-LTR circle formation,2-LTR circle formation,2-LTR circle formation,REACTOME
2,3' -UTR-mediated translational regulation,3' -UTR-mediated translational regulation,3' -UTR-mediated translational regulation,REACTOME
3,5-Phosphoribose 1-diphosphate biosynthesis,PRPP biosynthesis,PRPP biosynthesis,REACTOME
4,ABH2 mediated Reversal of Alkylation Damage,ABH2 mediated Reversal of Alkylation Damage,ABH2 mediated Reversal of Alkylation Damage,REACTOME
...,...,...,...,...
1751,hsa05020,Prion diseases,Prion diseases,KEGG
1752,hsa03320,PPAR signaling pathway,PPAR signaling pathway,KEGG
1753,hsa00620,Pyruvate metabolism,Pyruvate metabolism,KEGG
1754,hsa04070,Phosphatidylinositol signaling system,Phosphatidylinositol signaling system,KEGG
1755,hsa00532,Glycosaminoglycan biosynthesis - chondroitin s...,Glycosaminoglycan biosynthesis - chondroitin s...,KEGG

In [16]:
metadata

{'cached_ids': ['1_9606'],
 'cached_subqueries': [{'pathways': '1', 'taxonId': '9606'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 1756,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'name', 'dtype': 'object', 'n_missing': 0},
   {'name': 'title', 'dtype': 'object', 'n_missing': 0},
   {'name': 'description', 'dtype': 'object', 'n_missing': 0},
   {'name': 'source_database', 'dtype': 'object', 'n_missing': 0}]},
 'execution_time': 0.011638641357421875,
 'api_name': 'BioDBNet',
 'method': 'getpathways',
 'option': None}

## BioGRID

### Importing the API

In [17]:
from bioseq_dl import BioGRIDInterface

### Instantiating the API

In [18]:
instance = BioGRIDInterface()

### Making a request

In [19]:
response, metadata = instance.fetch_single(
    query={
        "geneList": ["P53", "CDK2", "BRCA1"],
    },
    method="interactions",
    parse=True,
    format="dataframe",
)
response

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,WWOX,BCC7|LFS1|P53|TRP53,D16S432E|FOR|FRA16D|HHCMA56|PRO0128|SCAR12|SDR...,9606,9606
1,CDC14A,BCC7|LFS1|P53|TRP53,cdc14|hCDC14,9606,9606
2,betaTub60D,Dmel\CG15450,143391_i_at|3t|B3t|BETA 60D|CG3401|D.m.BETA-60...,7227,7227
3,tamo,1323/07|1422/04|CG17117|Dm-HTH|Dmel\CG17117|Me...,60B|CG4057|Dmel\CG4057,7227,7227
4,exd,1323/07|1422/04|CG17117|Dm-HTH|Dmel\CG17117|Me...,CG8933|DExd|Dm-EXD|Dmel\CG8933|Dpbx|Pbx1|anon-...,7227,7227
...,...,...,...,...,...
10035,PRR5,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,FLJ20185k|PP610|PROTOR-1|PROTOR1,9606,9606
10036,RICTOR,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,AVO3|PIA|hAVO3,9606,9606
10037,BRCA1,JC310|MIP1|SIN1|SIN1b|SIN1g,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,9606,9606
10038,BRCA1,FLJ20185k|PP610|PROTOR-1|PROTOR1,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,9606,9606
10039,BRCA1,AVO3|PIA|hAVO3,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,9606,9606

In [20]:
response, metadata = instance.fetch_batch(
    queries=[
        {
            "geneList": ["P53", "CDK2", "BRCA1"],
        },
        {
            "geneList": ["BRCA2", "ATM", "CHEK2"],
        },
    ],
    method="interactions",
    parse=True,
    format="dataframe",
)
response

TypeError: bioseq_dl.core.interfaces.base.BaseAPIInterface._maybe_parse() got multiple values for keyword argument 'format'

In [21]:
metadata

{'cached_ids': ['P53', 'CDK2', 'BRCA1', 'BRCA2', 'ATM', 'CHEK2'],
 'cached_subqueries': [{'geneList': 'P53'},
  {'geneList': 'CDK2'},
  {'geneList': 'BRCA1'},
  {'geneList': 'BRCA2'},
  {'geneList': 'ATM'},
  {'geneList': 'CHEK2'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 6,
 'data_info': {'total_entries': 12069,
  'data_type': 'DataFrame',
  'columns': [{'name': 'interaction_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_a', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism_a', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism_b', 'dtype': 'int64', 'n_missing': 0}]},
 'execution_time': 2.5987625122070312e-05,
 'api_name': '',
 'method': 'interactions',
 'option': None,
 'source_api': 'BioGRID'}

In [ ]:
response, metadata = instance.fetch_single(
    query={
        "geneList": ["cdc27", "apc1", "apc2"],
        "taxId": "559292",
    },
    method="interactions",
    parse=True,
    format="dataframe",
)
response

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,APC1,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit 1|L000004053,559292,559292
1,CDC16,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit CDC16|L0000...,559292,559292
2,CDC23,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit CDC23|L0000...,559292,559292
3,CDC27,RSI1|TID2|anaphase promoting complex subunit 2...,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292
4,APC2,APC10|anaphase promoting complex subunit DOC1|...,RSI1|TID2|anaphase promoting complex subunit 2...,559292,559292
...,...,...,...,...,...
4423,APC1,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,anaphase promoting complex subunit 1|L000004053,559292,559292
4424,APC2,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,RSI1|TID2|anaphase promoting complex subunit 2...,559292,559292
4425,CDC27,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292
4426,APC1,MIND complex subunit DSN1|L000004645,anaphase promoting complex subunit 1|L000004053,559292,559292
4427,CDC27,MIND complex subunit DSN1|L000004645,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292

In [23]:
metadata

{'cached_ids': ['cdc27_559292', 'apc1_559292', 'apc2_559292'],
 'cached_subqueries': [{'geneList': 'cdc27', 'taxId': '559292'},
  {'geneList': 'apc1', 'taxId': '559292'},
  {'geneList': 'apc2', 'taxId': '559292'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 4428,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'interaction_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_a', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism_a', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism_b', 'dtype': 'int64', 'n_missing': 0}]},
 'execution_time': 0.07692670822143555,
 'api_name': 'BioGRID',
 'method': 'interactions',
 'option': None}

In [ ]:
response, metadata = instance.fetch_single(
    query={
        "geneList": ["cdc27", "apc1", "apc2"],
        "taxId": "559292",
    },
    method="interactions",
    parse=True,
    format="dataframe",
)
response

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,APC1,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit 1|L000004053,559292,559292
1,CDC16,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit CDC16|L0000...,559292,559292
2,CDC23,RSI1|TID2|anaphase promoting complex subunit 2...,anaphase promoting complex subunit CDC23|L0000...,559292,559292
3,CDC27,RSI1|TID2|anaphase promoting complex subunit 2...,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292
4,APC2,APC10|anaphase promoting complex subunit DOC1|...,RSI1|TID2|anaphase promoting complex subunit 2...,559292,559292
...,...,...,...,...,...
4423,APC1,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,anaphase promoting complex subunit 1|L000004053,559292,559292
4424,APC2,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,RSI1|TID2|anaphase promoting complex subunit 2...,559292,559292
4425,CDC27,CDK1|HSL5|SRM5|cyclin-dependent serine/threoni...,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292
4426,APC1,MIND complex subunit DSN1|L000004645,anaphase promoting complex subunit 1|L000004053,559292,559292
4427,CDC27,MIND complex subunit DSN1|L000004645,APC3|SNB1|anaphase promoting complex subunit C...,559292,559292

In [25]:
metadata

{'cached_ids': ['cdc27_559292', 'apc1_559292', 'apc2_559292'],
 'cached_subqueries': [{'geneList': 'cdc27', 'taxId': '559292'},
  {'geneList': 'apc1', 'taxId': '559292'},
  {'geneList': 'apc2', 'taxId': '559292'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 4428,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'interaction_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_a', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism_a', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism_b', 'dtype': 'int64', 'n_missing': 0}]},
 'execution_time': 0.07275032997131348,
 'api_name': 'BioGRID',
 'method': 'interactions',
 'option': None}

In [ ]:
response, metadata = instance.fetch_single(
    query={
        "geneList": ["MFS1"],
        "taxId": "9606",
    },
    method="interactions",
    parse=True,
    format="dataframe",
)
response.head(5)

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,MFAP2,ACMICD|ECTOL1|FBN|GPHYSD2|MASS|MFS1|OCTD|SGS|S...,MAGP|MAGP-1|MAGP1,9606,9606
1,FBN1,-,ACMICD|ECTOL1|FBN|GPHYSD2|MASS|MFS1|OCTD|SGS|S...,9606,9606
2,FBN1,GLC1A|GPOA|JOAG|JOAG1|TIGR|myocilin,ACMICD|ECTOL1|FBN|GPHYSD2|MASS|MFS1|OCTD|SGS|S...,9606,9606
3,FBN1,CSPG2|ERVR|GHAP|PG-M|WGN|WGN1,ACMICD|ECTOL1|FBN|GPHYSD2|MASS|MFS1|OCTD|SGS|S...,9606,9606
4,FBN1,SVAS|WBS|WS,ACMICD|ECTOL1|FBN|GPHYSD2|MASS|MFS1|OCTD|SGS|S...,9606,9606

In [27]:
metadata

{'cached_ids': ['MFS1_9606'],
 'cached_subqueries': [{'geneList': 'MFS1', 'taxId': '9606'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 39,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'interaction_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_a', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism_a', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism_b', 'dtype': 'int64', 'n_missing': 0}]},
 'execution_time': 0.00189208984375,
 'api_name': 'BioGRID',
 'method': 'interactions',
 'option': None}

In [ ]:
response, metadata = instance.fetch_single(
    query={"id": "103"}, method="interactions", parse=True, format="dataframe"
)
response

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,FLNC,JNKK|JNKK1|MAPKK4|MEK4|MKK4|PRKMK4|SAPKK-1|SAP...,ABP-280|ABP280A|ABPA|ABPL|FLN2|MFM5|MPD4,9606,9606
1,ACTN2,CMD1DD|CMH22|MYOP|RCM4,CMD1AA,9606,9606
2,FNTA,ACTRI|ACVR1A|ACVRLK2|ALK2|FOP|SKR1|TSRI,FPTA|PGGT1A|PTAR2,9606,9606
3,PML,DCML|IMD21|MONOMAC|NFE1B,MYL|PP8675|RNF71|TRIM19,9606,9606
4,STAT3,REPA2|RP-A p32|RP-A p34|RPA32,ADMIO|APRF|HIES,9606,9606
...,...,...,...,...,...
9995,RpS17,CG13167|Dmel\CG13167,BcDNA:RE44119|CG3922|D9|Dmel\CG3922|M|M(3)67|M...,7227,7227
9996,RpL15,CG13167|Dmel\CG13167,80Fi|CG17420|CG40199|DmRpL15|Dmel\CG17420|L15|...,7227,7227
9997,CG15423,Dmel\CG13168,Dmel\CG15423,7227,7227
9998,CG15549,Dmel\CG13168,BcDNA:AT07554|Dmel\CG15549,7227,7227
9999,CG15578,Dmel\CG13168,Dmel\CG15578,7227,7227

In [29]:
metadata

{'cached_ids': ['103'],
 'cached_subqueries': [{'id': '103'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 10000,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'interaction_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_a', 'dtype': 'object', 'n_missing': 0},
   {'name': 'synonyms_b', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism_a', 'dtype': 'int64', 'n_missing': 0},
   {'name': 'organism_b', 'dtype': 'int64', 'n_missing': 0}]},
 'execution_time': 0.13842201232910156,
 'api_name': 'BioGRID',
 'method': 'interactions',
 'option': None}

## Brenda

### Importing the API

In [1]:
from bioseq_dl import BrendaInterface

### Instantiating the API

In [2]:
instance = BrendaInterface()

### Making a request

In [ ]:
response, metadata = instance.fetch_single(
    query={"ecNumber": "1.1.1.10", "temperatureOptimum": "25"},
    method="getTemperatureOptimum",
    parse=False,
    format="json",
)
response

[{'literature': [656049],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Homo sapiens',
  'ecNumber': '1.1.1.10'},
 {'literature': [657322],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Homo sapiens',
  'ecNumber': '1.1.1.10'},
 {'literature': [656049],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Mus musculus',
  'ecNumber': '1.1.1.10'},
 {'literature': [656049],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Rattus norvegicus',
  'ecNumber': '1.1.1.10'},
 {'literature': [656049],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Cavia porcellus',
  'ecNumber': '1.1.1.10'},
 {'literature': [656049],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Mesocricetus auratus',
  'ecNumber': '1.1.1.10'},
 {'literature': [654438],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Mus musculus',
  'ecNumber': '1.1.1.10'},
 {'literature': [654438],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Homo sapiens',
  'ecNumber': '1.1.1.10'},
 {'literature': [655222],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Rattus norvegicus',
  'ecNumber': '1.1.1.10'},
 {'literature': [760730],
  'temperatureOptimumMaximum': None,
  'temperatureOptimum': '25',
  'commentary': 'assay at',
  'organism': 'Rhizomucor pusillus',
  'ecNumber': '1.1.1.10'}]

In [ ]:
response, metadata = instance.fetch_single(
    query={
        "ecNumber": "1.1.1.10",
        "organism": "Homo sapiens",
        # "kcatKmValue": "0.5"
    },
    method="getKmValue",
    parse=True,
    format="dataframe",
)
response

          ec      organism      km km_max          substrate
0   1.1.1.10  Homo sapiens   0.001   None              NADP+
1   1.1.1.10  Homo sapiens   0.002   None              NADPH
2   1.1.1.10  Homo sapiens   0.002   None              NADPH
3   1.1.1.10  Homo sapiens   0.077   None           diacetyl
4   1.1.1.10  Homo sapiens   0.077   None           diacetyl
5   1.1.1.10  Homo sapiens  0.0945   None           diacetyl
6   1.1.1.10  Homo sapiens    0.17   None               NADH
7   1.1.1.10  Homo sapiens    0.21   None         L-xylulose
8   1.1.1.10  Homo sapiens    0.22   None           diacetyl
9   1.1.1.10  Homo sapiens    0.85   None               NAD+
10  1.1.1.10  Homo sapiens     1.2   None  DL-glyceraldehyde
11  1.1.1.10  Homo sapiens     1.5   None            acetoin
12  1.1.1.10  Homo sapiens     1.6   None   dihydroxyacetone
13  1.1.1.10  Homo sapiens     1.9   None          D-threose
14  1.1.1.10  Homo sapiens     2.4   None        D-erythrose
15  1.1.1.10  Homo sapiens     2.5   None      L-erythrulose
16  1.1.1.10  Homo sapiens     4.2   None          L-threose
17  1.1.1.10  Homo sapiens     4.8   None         D-xylulose
18  1.1.1.10  Homo sapiens       5   None         D-ribulose
19  1.1.1.10  Homo sapiens      18   None         D-threitol
20  1.1.1.10  Homo sapiens      25   None            xylitol
21  1.1.1.10  Homo sapiens      26   None           diacetyl
22  1.1.1.10  Homo sapiens      31   None           diacetyl
23  1.1.1.10  Homo sapiens      95   None              NADPH
24  1.1.1.10  Homo sapiens      97   None              NADPH

In [4]:
metadata

{'cached_ids': ['1.1.1.10_Homo sapiens'],
 'cached_subqueries': [{'ecNumber': '1.1.1.10', 'organism': 'Homo sapiens'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 25,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'ec', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism', 'dtype': 'object', 'n_missing': 0},
   {'name': 'km', 'dtype': 'object', 'n_missing': 0},
   {'name': 'km_max', 'dtype': 'object', 'n_missing': 25},
   {'name': 'substrate', 'dtype': 'object', 'n_missing': 0}]},
 'execution_time': 0.007028102874755859,
 'api_name': 'BRENDA',
 'method': 'getKmValue',
 'option': None}

In [ ]:
response, metadata = instance.fetch_single(
    query={
        # "ecNumber": "1.1.1.10",
        "organism": "Homo sapiens",
        "temperatureRange": "25-37",
    },
    method="getTemperatureRange",
    parse=True,
    format="dataframe",
)
response

            ec      organism temperature_range temperature_range_max
0    1.1.1.188  Homo sapiens                25                    37
1     2.1.1.77  Homo sapiens                25                    65
2     2.4.1.38  Homo sapiens                25                    45
3     2.4.1.90  Homo sapiens                25                    45
4     2.7.1.21  Homo sapiens                25                    37
5      2.8.2.2  Homo sapiens                25                    50
6      3.1.8.1  Homo sapiens                25                    50
7     3.1.11.1  Homo sapiens                25                    37
8   3.4.21.108  Homo sapiens                25                    55
9      3.5.1.1  Homo sapiens                25                    60
10    3.6.4.10  Homo sapiens                25                    70
11    3.13.2.1  Homo sapiens                25                    49
12    4.6.1.19  Homo sapiens                25                    30
13     5.6.2.1  Homo sapiens                25                    37

In [6]:
metadata

{'cached_ids': ['25-37_Homo sapiens'],
 'cached_subqueries': [{'organism': 'Homo sapiens',
   'temperatureRange': '25-37'}],
 'fetched_ids': [],
 'fetched_subqueries': [],
 'failed_ids': [],
 'fetched_length': 0,
 'data_info': {'total_entries': 14,
  'data_type': pandas.core.frame.DataFrame,
  'columns': [{'name': 'ec', 'dtype': 'object', 'n_missing': 0},
   {'name': 'organism', 'dtype': 'object', 'n_missing': 0},
   {'name': 'temperature_range', 'dtype': 'object', 'n_missing': 0},
   {'name': 'temperature_range_max', 'dtype': 'object', 'n_missing': 0}]},
 'execution_time': 0.0031414031982421875,
 'api_name': 'BRENDA',
 'method': 'getTemperatureRange',
 'option': None}

## Chembl

### Importing the API

In [17]:
from bioseq_dl import ChEMBLInterface

### Instantiating the API

In [18]:
instance = ChEMBLInterface()

### Making a Request

A number of methods are available to make requests to the database.

- `target`: Gather protein and non-protein targets information.
- `assay`: Assay details as reported in ChEMBL.
- `cell_line`: Cell line information.
- `molecule`: Molecule information, including properties, structural representations and synonyms.
- `activity`: Activity values recorded in an Assay.
- `binding_site`: Target binding site definition
- `substructure`: Substructure search for molecules.
- `similarity`: Similarity search for molecules.

For `target`, `assay`, `cell_line` and `molecule` you can define a query with either 'query' or 'filters' parameters. 

query: str or list of str
    Single identifier or list of identifiers to search for.

filters: dict
    Dictionary of filters to apply to the search. The keys are: `field`, `filter_type`, `value`.
More information of what fields and filter types are available in the [ChEMBL API documentation](https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services#filtering-and-ordering).

### Important
Additionaly for this API you can set the number of pages to fetch with `pages_to_fetch` parameter. By default it will fetch only the first page. Use -1 to fetch all available pages.

Using Target

In [ ]:
response, _ = instance.fetch_single(
    query={"filters": [{"field": "gene_symbol", "filter_type": "icontains", "value": "EGFR"}]},
    method="target",
    parse=True,
    format="dataframe",
)
response.head(5)

,cross_references,organism,pref_name,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Maltase-glucoamylase,False,CHEMBL2074,"[{'accession': 'O43451', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,ATP-binding cassette sub-family C member 9,False,CHEMBL1971,"[{'accession': 'O60706', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,"cGMP-specific 3',5'-cyclic phosphodiesterase",False,CHEMBL1827,"[{'accession': 'O76074', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Voltage-dependent T-type calcium channel subun...,False,CHEMBL1859,"[{'accession': 'O95180', 'component_descriptio...",SINGLE PROTEIN,9606
4,[],Ascaris suum,Nicotinic acetylcholine receptor alpha subunit,False,CHEMBL1884,"[{'accession': 'O96760', 'component_descriptio...",SINGLE PROTEIN,6253

Using Molecule

In [ ]:
response, _ = instance.fetch_single(
    query={
        "filters": [
            {
                "field": "molecule_structures__canonical_smiles",
                "filter_type": "icontains",
                "value": "c1ccccc1N",
            }
        ]
    },
    method="molecule",
    parse=True,
    format="dataframe",
)
response.head(5)

,atc_classifications,availability_type,biotherapeutic,black_box_warning,chemical_probe,chirality,cross_references,dosed_ingredient,first_approval,first_in_class,...,prodrug,structure_type,therapeutic_flag,topical,usan_stem,usan_stem_definition,usan_substem,usan_year,veterinary,withdrawn_flag
0,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
1,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
2,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
3,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
4,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False

In [ ]:
response, _ = instance.fetch_single(
    query={"filters": [{"field": "name", "filter_type": "iexact", "value": "Imatinib"}]},
    method="molecule",
    parse=True,
    format="dataframe",
)
response.head(5)

,atc_classifications,availability_type,biotherapeutic,black_box_warning,chemical_probe,chirality,cross_references,dosed_ingredient,first_approval,first_in_class,...,prodrug,structure_type,therapeutic_flag,topical,usan_stem,usan_stem_definition,usan_substem,usan_year,veterinary,withdrawn_flag
0,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
1,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
2,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
3,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
4,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False

In [ ]:
response, _ = instance.fetch_single(
    query={
        "filters": [
            {"field": "molecule_properties__mw_freebase", "filter_type": "lte", "value": "300"},
            {"field": "pref_name", "filter_type": "iendswith", "value": "nib"},
        ]
    },
    method="molecule",
    parse=True,
    format="dataframe",
)
response.head(5)

,atc_classifications,availability_type,biotherapeutic,black_box_warning,chemical_probe,chirality,cross_references,dosed_ingredient,first_approval,first_in_class,...,prodrug,structure_type,therapeutic_flag,topical,usan_stem,usan_stem_definition,usan_substem,usan_year,veterinary,withdrawn_flag
0,[],NaN,None,0,0,2,[],False,NaN,0,...,0,MOL,False,False,-anib,angiogenesis inhibitors,-anib,2000.0,0,False
1,[L04AF08],1.0,None,1,0,1,[],False,2023.0,0,...,0,MOL,True,False,-tinib,tyrosine kinase inhibitors: tyrosine kinase in...,-tinib (-citinib),NaN,0,False
2,[],NaN,None,0,0,1,[{'xref_id': 'https://searchusan.ama-assn.org/...,False,NaN,0,...,0,MOL,False,False,-tinib,tyrosine kinase inhibitors: tyrosine kinase in...,-tinib (-brutinib),2021.0,0,False

Using Assay

In [ ]:
response, _ = instance.fetch_single(
    query={"filters": [{"field": "assay_type", "filter_type": "iexact", "value": "B"}]},
    method="assay",
    parse=True,
    format="dataframe",
)
response.head(5)

,aidx,assay_category,assay_cell_type,assay_chembl_id,assay_classifications,assay_group,assay_organism,assay_parameters,assay_strain,assay_subcellular_fraction,...,confidence_score,description,document_chembl_id,relationship_description,relationship_type,src_assay_id,src_id,target_chembl_id,tissue_chembl_id,variant_sequence
0,CLD0,None,None,CHEMBL615117,[],None,None,[],None,None,...,8,The compound was tested for the in vitro inhib...,CHEMBL1125582,Homologous protein target assigned,H,None,1,CHEMBL2741,None,None
1,CLD0,None,None,CHEMBL615119,[],None,None,[],None,None,...,0,None,CHEMBL1133101,Default value - Target has yet to be curated,U,None,1,CHEMBL2362975,None,None
2,CLD0,None,None,CHEMBL615120,[],None,Bos taurus,[],None,Membrane,...,4,Binding affinity against A2 adenosine receptor...,CHEMBL1149169,Homologous protein target assigned,H,None,1,CHEMBL2094257,CHEMBL3638255,None
3,CLD0,None,None,CHEMBL615132,[],None,None,[],None,None,...,8,Concentration that cause 50% activation of hum...,CHEMBL1135472,Homologous protein target assigned,H,None,1,CHEMBL2903,None,None
4,CLD0,None,None,CHEMBL615133,[],None,None,[],None,None,...,8,Inhibition of partially purified 15-lipoxygena...,CHEMBL1124599,Homologous protein target assigned,H,None,1,CHEMBL2903,None,None

In [ ]:
response, _ = instance.fetch_single(
    query={"filters": [{"field": "description", "filter_type": "icontains", "value": "toxicity"}]},
    method="target",
    parse=True,
    format="dataframe",
    pages_to_fetch=-1,
)
response.head(5)

,cross_references,organism,pref_name,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Maltase-glucoamylase,False,CHEMBL2074,"[{'accession': 'O43451', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,ATP-binding cassette sub-family C member 9,False,CHEMBL1971,"[{'accession': 'O60706', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,"cGMP-specific 3',5'-cyclic phosphodiesterase",False,CHEMBL1827,"[{'accession': 'O76074', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Voltage-dependent T-type calcium channel subun...,False,CHEMBL1859,"[{'accession': 'O95180', 'component_descriptio...",SINGLE PROTEIN,9606
4,[],Ascaris suum,Nicotinic acetylcholine receptor alpha subunit,False,CHEMBL1884,"[{'accession': 'O96760', 'component_descriptio...",SINGLE PROTEIN,6253

Using substructure search

In [ ]:
response, _ = instance.fetch_single(
    query="C1=CC=CC=C1", method="substructure", parse=True, format="dataframe"
)
response.head(5)

,atc_classifications,availability_type,biotherapeutic,black_box_warning,chemical_probe,chirality,cross_references,dosed_ingredient,first_approval,first_in_class,...,prodrug,structure_type,therapeutic_flag,topical,usan_stem,usan_stem_definition,usan_substem,usan_year,veterinary,withdrawn_flag
0,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
1,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
2,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
3,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False
4,[],-1,None,0,0,-1,[],False,None,-1,...,-1,MOL,False,False,None,None,None,None,-1,False

Using Activity

In [ ]:
response, _ = instance.fetch_single(
    query={"target_chembl_id": "CHEMBL1824", "pchembl_value": 5.62},
    method="activity",
    pages_to_fetch=1,
    parse=True,
    format="dataframe",
)
response

        assay_id  type units   value
0   CHEMBL650385  IC50    uM     2.4
1   CHEMBL880259  IC50    uM     2.4
2  CHEMBL1073381  IC50    uM     2.4
3  CHEMBL1932748  IC50    nM  2421.0
4  CHEMBL2320919  IC50    uM    2.38
5  CHEMBL3993804  IC50    nM  2400.0
6  CHEMBL5444475  IC50    nM  2400.0

In [ ]:
response, _ = instance.fetch_single(
    query={"target_chembl_id": "CHEMBL5169197"},
    method="activity",
    pages_to_fetch=1,
    parse=False,
    format="dataframe",
)
response

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771458,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,4.0
1,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771459,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,33.0
2,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771460,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,35.0
3,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771461,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,1.2
4,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771462,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,2.4
5,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771463,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,8.3
6,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771464,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,8.9
7,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771465,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,2.2
8,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24771466,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5126413,Inhibition of GST-tagged human IDAX (130 to 18...,B,None,None,BAO_0000190,...,Homo sapiens,CXXC-type zinc finger protein 4,9606,None,None,IC50,uM,UO_0000065,None,23.0

Using Binding Site

In [ ]:
response, _ = instance.fetch_single(
    query={"target_chembl_id": "CHEMBL1824"},
    method="binding_site",
    pages_to_fetch=1,
    parse=True,
    format="dataframe",
)
response

,site_components,site_id,site_name
0,"[{'component_id': 4909, 'domain': {'domain_des...",2,"UDP-glucuronosyltransferase 1-10, UDPGT domain"
1,"[{'component_id': 5575, 'domain': {'domain_des...",3,"Mitogen-activated protein kinase 8, Pkinase do..."
2,"[{'component_id': 118, 'domain': {'domain_desc...",4,"Inosine-5'-monophosphate dehydrogenase 1, IMPD..."
3,"[{'component_id': 397, 'domain': {'domain_desc...",5,"Dopamine D1 receptor, 7tm_1 domain"
4,"[{'component_id': 218, 'domain': {'domain_desc...",6,"GABA transporter 1, SNF domain"
5,"[{'component_id': 1835, 'domain': {'domain_des...",7,"LDL-associated phospholipase A2, PAF-AH_p_II d..."
6,"[{'component_id': 2632, 'domain': {'domain_des...",8,"Purinergic receptor P2Y1, 7tm_1 domain"
7,"[{'component_id': 873, 'domain': {'domain_desc...",9,"3-phosphoinositide dependent protein kinase-1,..."
8,"[{'component_id': 970, 'domain': {'domain_desc...",10,"Tyrosine-protein kinase CSK, Pkinase_Tyr domain"
9,"[{'component_id': 3106, 'domain': {'domain_des...",11,"Carbonic anhydrase VA, Carb_anhydrase domain"
10,"[{'component_id': 2231, 'domain': {'domain_des...",12,"Phosphodiesterase 3B, PDEase_I domain"
11,"[{'component_id': 1388, 'domain': {'domain_des...",13,"Glycine transporter 2, SNF domain"
12,"[{'component_id': 2230, 'domain': {'domain_des...",14,"11-beta-hydroxysteroid dehydrogenase 1, adh_sh..."
13,"[{'component_id': 1377, 'domain': {'domain_des...",15,"Monoamine oxidase B, Amino_oxidase domain"
14,"[{'component_id': 1711, 'domain': {'domain_des...",16,"Lactase-glycosylceramidase, Glyco_hydro_1 domain"
15,"[{'component_id': 1188, 'domain': {'domain_des...",17,"Mu opioid receptor, 7tm_1 domain"
16,"[{'component_id': 2704, 'domain': {'domain_des...",18,"Thymidylate kinase, Thymidylate_kin domain"
17,"[{'component_id': 3285, 'domain': {'domain_des...",19,"Excitatory amino acid transporter 2, SDF domain"
18,"[{'component_id': 2600, 'domain': {'domain_des...",20,"Group IID secretory phospholipase A2, Phosphol..."
19,"[{'component_id': 2748, 'domain': {'domain_des...",21,"Serotonin 2c (5-HT2c) receptor, 7tm_1 domain"

## Chebi

### Importing the API

In [33]:
from bioseq_dl import ChEBIInterface

### Instantiating the API

In [34]:
instance = ChEBIInterface()

### Making a Request

A number of methods are available to make requests to the database.

- `compound`: Retrieve information about a single compound.
- `compounds`: Retrieve information about one or more compounds.
- `es_search`: Perform a text search in the elasticsearch documents, it tries to get an exact match in the first place, otherwise, it is executed a text search
- `ontology-children`:
- `ontology-parents`:

In [ ]:
response, _ = instance.fetch_single(
    query={"chebi_ids": ["CHEBI:18357", "CHEBI:29033"]}, method="compounds", parse=True, format="dataframe"
)
response.head(5)

,id,ascii_name,chebi_accession,formula,charge,mass,monoisotopic_mass,species,species_accession,component,...,is_r_group,definition,is_released,modified_on,name,names,ontology_relations,roles_classification,secondary_ids,stars
0,CHEBI:18357,(R)-noradrenaline,CHEBI:18357,C8H11NO3,0,169.180,169.07389,Mus musculus,10090,None,...,False,The <i>R</i>-enantiomer of noradrenaline.,True,2019-11-20T17:35:17Z,(<i>R</i>)-noradrenaline,"{'SYNONYM': [{'name': 'Noradrenaline', 'status...","{'incoming_relations': [{'init_id': 167178, 'i...","[{'application': True, 'chemical_role': False,...","[CHEBI:1, CHEBI:14668, CHEBI:25592, CHEBI:4372...",3
1,CHEBI:29033,iron(2+),CHEBI:29033,Fe,2,55.845,55.93384,"[Homo sapiens, Saccharomyces cerevisiae, Mus m...","[9606, 4932, 10090]","[None, None, None]",...,False,None,True,2019-07-25T14:48:59Z,iron(2+),{'UNIPROT NAME': [{'name': 'Fe<small><sup>2+</...,"{'incoming_relations': [{'init_id': 75832, 'in...","[{'application': False, 'chemical_role': False...","[CHEBI:13319, CHEBI:13321, CHEBI:21129, CHEBI:...",3

Using es_search

In [ ]:
response, _ = instance.fetch_batch(
    queries=[{"term": "aspirin"}], method="es_search", parse=True, format="dataframe"
)
response.head(5)

,index,type,id,score,chebi_accession,name,ascii_name,stars,default_structure,definition,formula,monoisotopicmass,inchikey,inchi,smiles,charge,mass,structures
0,chebi-prod-compounds-11112025,_doc,138615,56.90262,CHEBI:138615,aspirin-triggered resolvin D3,aspirin-triggered resolvin D3,3,3100105.0,A member of the class of resolvins that is (5<...,C22H32O5,376.22497,QBTJOLCUKWLTIC-AXRBAIMGSA-N,InChI=1S/C22H32O5/c1-2-3-7-12-19(23)14-10-6-11...,CC/C=CC[C@@H](O)/C=C/C=CC[C@@H](O)/C=C/C=C/C=C...,0.0,376.493,3100105
1,chebi-prod-compounds-11112025,_doc,138616,56.90262,CHEBI:138616,aspirin-triggered resolvin D4,aspirin-triggered resolvin D4,3,3100113.0,A member of the class of resolvins that is (6<...,C22H32O5,376.22497,YKPLJNOOLKUEBS-MMOUQCFBSA-N,InChI=1S/C22H32O5/c1-2-3-11-14-19(23)15-12-9-7...,CC/C=CC[C@@H](O)/C=C/C=CC/C=CC=CC=C[C@@H](O)[C...,0.0,376.493,3100113
2,chebi-prod-compounds-11112025,_doc,138617,56.90262,CHEBI:138617,aspirin-triggered resolvin D5,aspirin-triggered resolvin D5,3,3100158.0,A member of the class of resolvins that is (5<...,C22H32O4,360.23006,JBRPFYYLEQERPG-RIVVZJRMSA-N,InChI=1S/C22H32O4/c1-2-3-10-15-20(23)16-11-7-5...,CC/C=CC[C@@H](O)/C=C/C=CC/C=CC=C[C@@H](O)/C=CC...,0.0,360.494,3100158
3,chebi-prod-compounds-11112025,_doc,138618,56.90262,CHEBI:138618,aspirin-triggered resolvin D6,aspirin-triggered resolvin D6,3,3100170.0,A member of the class of resolvins that is (5<...,C22H32O4,360.23006,JKPUWSZSJINVLB-VDOHSOROSA-N,InChI=1S/C22H32O4/c1-2-3-12-15-20(23)16-13-10-...,CC/C=CC[C@@H](O)/C=C/C=CC/C=CC/C=CC=C[C@@H](O)...,0.0,360.494,3100170
4,chebi-prod-compounds-11112025,_doc,138614,55.99210,CHEBI:138614,aspirin-triggered resolvin D2,aspirin-triggered resolvin D2,3,3486175.0,A member of the class of resolvins that is (4<...,C22H32O5,376.22497,IKFAUGXNBOBQDM-FYSWCGKBSA-N,InChI=1S/C22H32O5/c1-2-3-9-16-20(24)21(25)17-1...,CC/C=CC[C@@H](O)[C@H](O)/C=C/C=C/C=CC=C[C@@H](...,0.0,376.493,3486175

In [ ]:
response, _ = instance.fetch_batch(
    queries=[{"term": "InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)"}],
    method="es_search",
    parse=True,
    format="dataframe",
)
response.head(5)

,index,type,id,score,chebi_accession,name,ascii_name,stars,default_structure,definition,formula,monoisotopicmass,inchikey,inchi,smiles,charge,mass,structures
0,chebi-prod-compounds-11112025,_doc,15365,11.698464,CHEBI:15365,acetylsalicylic acid,acetylsalicylic acid,3,94,A member of the class of benzoic acids that is...,C9H8O4,180.04226,BSYNRYMUTXBXSQ-UHFFFAOYSA-N,InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)...,CC(=O)Oc1ccccc1C(=O)O,0,180.159,"[50786, 94]"

Using ontology-children

In [ ]:
response, _ = instance.fetch_batch(
    queries=[{"chebi_id": "CHEBI:18357"}], method="ontology-children", parse=True, format="dataframe"
)
response

      id chebi_accession                                 ontology_relations
0  18357     CHEBI:18357  {'incoming_relations': [{'init_id': 167178, 'i...

using ontology-parents

In [ ]:
response, _ = instance.fetch_batch(
    queries=[{"chebi_id": "CHEBI:18357"}], method="ontology-parents", parse=True, format="dataframe"
)
response

      id chebi_accession                                 ontology_relations
0  18357     CHEBI:18357  {'outgoing_relations': [{'init_id': 18357, 'in...

## Gen Ontology

### Importing the API

In [41]:
from bioseq_dl import GenOntologyInterface

### Instantiating the API

In [42]:
instance = GenOntologyInterface()

### Making a Request

In [ ]:
response, _ = instance.fetch_single(
    query="GO:0005783", method="bioentity-function", parse=True, format="dataframe"
)
response.head(5)

,label,name,tax_id,organism,evidence_type,evidence,synonym
0,Vcp,valosin containing protein,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[AAA ATPase p97, CDC48, p97, p97/VCP]"
1,Aqp11,aquaporin 11,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[1700015P13Rik, sjds]"
2,Erp44,endoplasmic reticulum protein 44,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[1110001E24Rik, Txndc4]"
3,Synpo,synaptopodin,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[9030217H17Rik, 9330140I15Rik]"
4,Ngly1,N-glycanase 1,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[1110002C09Rik, PNGase, Png1]"

In [ ]:
response, _ = instance.fetch_batch(
    queries=[
        "GO:0005783",
        "GO:0005789",
        "GO:0009922",
        "GO:0034625",
        "GO:0034626",
        "GO:0019367",
        "GO:0035338",
        "GO:0030148",
        "GO:0006636",
        "GO:0042761",
    ],
    method="bioentity-function",
    parse=True,
    format="dataframe",
)
response

,label,name,tax_id,organism,evidence_type,evidence,synonym
0,Vcp,valosin containing protein,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[AAA ATPase p97, CDC48, p97, p97/VCP]"
1,Aqp11,aquaporin 11,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[1700015P13Rik, sjds]"
2,Erp44,endoplasmic reticulum protein 44,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[1110001E24Rik, Txndc4]"
3,Synpo,synaptopodin,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[9030217H17Rik, 9330140I15Rik]"
4,Ngly1,N-glycanase 1,NCBITaxon:10090,Mus musculus,IPI,ECO:0000353,"[1110002C09Rik, PNGase, Png1]"
...,...,...,...,...,...,...,...
995,Csa_3G114430,Very-long-chain (3R)-3-hydroxyacyl-CoA dehydra...,NCBITaxon:3659,Cucumis sativus,IBA,ECO:0000318,"[UniProtKB:A0A0A0L3F8, PTN004221607]"
996,GSMUA_204600.1,(wild Malaysian banana) hypothetical protein,NCBITaxon:214687,Musa acuminata subsp. malaccensis,IBA,ECO:0000318,"[UniProtKB:A0A804I7D0, PTN004237358]"
997,Csa_6G303230,Very-long-chain (3R)-3-hydroxyacyl-CoA dehydra...,NCBITaxon:3659,Cucumis sativus,IBA,ECO:0000318,"[UniProtKB:A0A0A0KG29, PTN004221664]"
998,AFUA_5G02760,Elongation of fatty acids protein,NCBITaxon:330879,Aspergillus fumigatus Af293,IBA,ECO:0000318,"[UniProtKB:Q4WEE9, PTN002597222]"
999,103975400,Very-long-chain (3R)-3-hydroxyacyl-CoA dehydra...,NCBITaxon:214687,Musa acuminata subsp. malaccensis,IBA,ECO:0000318,"[UniProtKB:A0A804I408, PTN004221623]"

In [ ]:
response, _ = instance.fetch_single(
    method="bioentity-function", query="GO:0006915", parse=True, format="dataframe"
)
response.head(5)

,label,name,tax_id,organism,evidence_type,evidence,synonym
0,Hnf1b,HNF1 homeobox B,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[HNF-1Beta, Hnf1beta, LFB3, Tcf-2, Tcf2, hepat..."
1,Ctnnb1,catenin beta 1,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[Catnb, beta catenin, beta-catenin, catenin (c..."
2,Cflar,CASP8 and FADD-like apoptosis regulator,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[2310024N18Rik, A430105C05Rik, Cash, Casper, F..."
3,Men1,multiple endocrine neoplasia 1,NCBITaxon:10090,Mus musculus,IDA,ECO:0000314,menin
4,Men1,multiple endocrine neoplasia 1,NCBITaxon:10090,Mus musculus,IGI,ECO:0000316,menin

In [ ]:
response, _ = instance.fetch_batch(
    method="bioentity-function", queries=["GO:0008150", "GO:0006915"], parse=True, format="dataframe"
)
response

,label,name,tax_id,organism,evidence_type,evidence,synonym
0,Hnf1b,HNF1 homeobox B,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[HNF-1Beta, Hnf1beta, LFB3, Tcf-2, Tcf2, hepat..."
1,Ctnnb1,catenin beta 1,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[Catnb, beta catenin, beta-catenin, catenin (c..."
2,Cflar,CASP8 and FADD-like apoptosis regulator,NCBITaxon:10090,Mus musculus,IMP,ECO:0000315,"[2310024N18Rik, A430105C05Rik, Cash, Casper, F..."
3,Men1,multiple endocrine neoplasia 1,NCBITaxon:10090,Mus musculus,IDA,ECO:0000314,menin
4,Men1,multiple endocrine neoplasia 1,NCBITaxon:10090,Mus musculus,IGI,ECO:0000316,menin
...,...,...,...,...,...,...,...
195,ogfr1,opioid growth factor receptor 1,NCBITaxon:7955,Danio rerio,ND,ECO:0000307,zgc:162182
196,cuedc1b,CUE domain containing 1b,NCBITaxon:7955,Danio rerio,ND,ECO:0000307,zgc:162271
197,lyrm5b,LYR motif containing 5b,NCBITaxon:7955,Danio rerio,ND,ECO:0000307,"[wu:fb39e10, zgc:162127]"
198,zgc:162060,zgc:162060,NCBITaxon:7955,Danio rerio,ND,ECO:0000307,si:dkey-83f18.1
199,morc3b,MORC family CW-type zinc finger 3b,NCBITaxon:7955,Danio rerio,ND,ECO:0000307,"[cb561, sb:cb561, sb:cb69, zgc:101052]"

In [ ]:
response, _ = instance.fetch_batch(
    method="ontology-term", queries=["GO:0008150", "GO:0006915"], parse=True, format="dataframe"
)
response

,go_term,label,definition
0,GO:0008150,biological_process,A biological process is the execution of a gen...
1,GO:0006915,apoptotic process,A programmed cell death process which begins w...

## Interpro

### Importing the API

In [ ]:
from bioseq_dl import InterproInterface

### Instantiating the API

In [51]:
instance = InterproInterface()

### Making a Request

In [52]:
queries = [
    {
        "db": "InterPro",
        "modifiers": {},
        "filters": [{"type": "protein", "db": "reviewed", "value": "Q29537"}],
    },
    {
        "db": "InterPro",
        "modifiers": {},
        "filters": [{"type": "protein", "db": "reviewed", "value": "P05067"}],
    },
]

In [53]:
queries = [
    {
        "db": "InterPro",
        "modifiers": {},
        "filters": [
            {"type": "protein", "db": "reviewed", "value": "A1L3X0"},
            {"type": "taxonomy", "db": "uniprot", "value": 9606},
        ],
    }
]

In [ ]:
response, _ = instance.fetch_batch(
    queries=queries, method="entry", pages_to_fetch=1, parse=True, format="dataframe"
)
response

,accession,length,organism_id,protein_source_db,in_alphafold,interpro_accession,name,type,source_database,integrated,...,prosite,smart,prints,panther,cathgene3d,ssf,go_identifier,go_name,go_category,locations
0,a1l3x0,281,9606,reviewed,True,IPR002076,ELO family,family,interpro,None,...,None,None,None,{'PTHR11157': 'FATTY ACID ACYL TRANSFERASE-REL...,None,None,"[GO:0009922, GO:0016020]","[fatty acid elongase activity, membrane]","[molecular_function, cellular_component]","{'fragments': [{'start': 24, 'end': 266, 'dc-s..."
1,a1l3x0,281,9606,reviewed,True,IPR030457,"ELO family, conserved site",conserved_site,interpro,None,...,{'PS01188': 'ELO family signature'},None,None,None,None,None,None,None,None,"{'fragments': [{'start': 143, 'end': 151, 'dc-..."
2,a1l3x0,281,9606,reviewed,True,IPR033670,Elongation of very long chain fatty acids prot...,family,interpro,None,...,None,None,None,None,None,None,"[GO:0009922, GO:0019367, GO:0042761, GO:0005783]","[fatty acid elongase activity, fatty acid elon...","[molecular_function, biological_process, biolo...","{'fragments': [{'start': 1, 'end': 281, 'dc-st..."

Search Interpro Id IPR036669

In [ ]:
query = {
    "id": "IPR002223",
    "db": "InterPro",
}

Search uniProt id Q29537

In [ ]:
query = {
    "db": "InterPro",
    "modifiers": {},
    "filters": [{"type": "protein", "db": "reviewed", "value": "Q29537"}],
}

In [ ]:
query = {
    "db": "InterPro",
    "modifiers": {},
    "filters": [{"type": "protein", "db": "reviewed", "value": "P05067"}],
}

In [ ]:
instance.fetch_single(query=query, method="entry", pages_to_fetch=1, parse=True, format="dataframe")

Cache_key: InterPro_{}_[{'type': 'protein', 'db': 'reviewed', 'value': 'P05067'}]_entry
Fetching data from InterPro API with URL: https://www.ebi.ac.uk:443/interpro/api/entry/InterPro/protein/reviewed/P05067/

,accession,length,organism_id,protein_source_db,in_alphafold,interpro_accession,name,type,source_database,integrated,...,prosite,smart,prints,panther,cathgene3d,ssf,go_identifier,go_name,go_category,locations
0,p05067,770,9606,reviewed,True,IPR002223,Pancreatic trypsin inhibitor Kunitz domain,domain,interpro,None,...,None,{'SM00131': 'BPTI/Kunitz family of serine prot...,{'PR00759': 'BASICPTASE'},None,None,None,GO:0004867,serine-type endopeptidase inhibitor activity,molecular_function,"{'fragments': [{'start': 288, 'end': 342, 'dc-..."
1,p05067,770,9606,reviewed,True,IPR008154,"Amyloidogenic glycoprotein, extracellular",domain,interpro,None,...,None,{'SM00006': 'amyloid A4'},None,None,None,None,None,None,None,"{'fragments': [{'start': 24, 'end': 189, 'dc-s..."
2,p05067,770,9606,reviewed,True,IPR008155,Amyloidogenic glycoprotein,family,interpro,None,...,None,None,{'PR00203': 'AMYLOIDA4'},{'PTHR23103': 'ALZHEIMER'S DISEASE BETA-AMYLOI...,None,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 10, 'end': 770, 'dc-s..."
3,p05067,770,9606,reviewed,True,IPR011178,"Amyloidogenic glycoprotein, copper-binding",domain,interpro,None,...,None,None,None,None,None,None,GO:0046914,transition metal ion binding,molecular_function,"{'fragments': [{'start': 132, 'end': 188, 'dc-..."
4,p05067,770,9606,reviewed,True,IPR011993,PH-like domain superfamily,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:2.30.29.30': 'Pleckstrin-homology doma...,None,None,None,None,"{'fragments': [{'start': 742, 'end': 770, 'dc-..."
5,p05067,770,9606,reviewed,True,IPR013803,"Amyloidogenic glycoprotein, amyloid-beta peptide",domain,interpro,None,...,None,None,{'PR00204': 'BETAAMYLOID'},None,None,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 675, 'end': 713, 'dc-..."
6,p05067,770,9606,reviewed,True,IPR015849,"Amyloidogenic glycoprotein, heparin-binding",domain,interpro,None,...,None,None,None,None,None,None,GO:0008201,heparin binding,molecular_function,"{'fragments': [{'start': 31, 'end': 131, 'dc-s..."
7,p05067,770,9606,reviewed,True,IPR019543,Beta-amyloid precursor protein C-terminal,domain,interpro,None,...,None,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 716, 'end': 766, 'dc-..."
8,p05067,770,9606,reviewed,True,IPR019744,"Amyloidogenic glycoprotein, copper-binding dom...",conserved_site,interpro,None,...,{'PS00319': 'Amyloid precursor protein (APP) c...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 181, 'end': 188, 'dc-..."
9,p05067,770,9606,reviewed,True,IPR019745,"Amyloidogenic glycoprotein, intracellular doma...",conserved_site,interpro,None,...,{'PS00320': 'Amyloid precursor protein (APP) i...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 756, 'end': 763, 'dc-..."
10,p05067,770,9606,reviewed,True,IPR020901,"Proteinase inhibitor I2, Kunitz, conserved site",conserved_site,interpro,None,...,{'PS00280': 'Pancreatic trypsin inhibitor (Kun...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 319, 'end': 337, 'dc-..."
11,p05067,770,9606,reviewed,True,IPR024329,"Amyloidogenic glycoprotein, E2 domain",domain,interpro,None,...,None,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 367, 'end': 565, 'dc-..."
12,p05067,770,9606,reviewed,True,IPR036176,E2 domain superfamily,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:1.20.120.770': 'Amyloid precursor prot...,"{'SSF109843': 'CAPPD, an extracellular domain ...",None,None,None,"{'fragments': [{'start': 363, 'end': 580, 'dc-..."
13,p05067,770,9606,reviewed,True,IPR036454,"Amyloidogenic glycoprotein, heparin-binding do...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:3.90.570.10': 'Amyloidogenic glycoprot...,{'SSF56491': 'A heparin-binding domain'},GO:0008201,heparin binding,molecular_function,"{'fragments': [{'start': 17, 'end': 123, 'dc-s..."
14,p05067,770,9606,reviewed,True,IPR036669,"Amyloidogenic glycoprotein, copper-binding dom...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:3.30.1490.140': 'Amyloidogenic glycopr...,{'SSF89811': 'Amyloid beta a4 protein copper b...,GO:0046914,transition metal ion binding,molecular_function,"{'fragments': [{'start': 124, 'end': 189, 'dc-..."
15,p05067,770,9606,reviewed,True,IPR036880,Pancreatic trypsin inhibitor Kunitz domain sup...,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:4.10.410.10': 'Pancreatic trypsin inhi...,{'SSF57362': 'BPTI-like'},GO:0004867,serine-type endopeptidase inhibitor activity,molecular_function,"{'fragments': [{'start': 279, 'end': 352, 'dc-..."
16,p05067,770,9606,reviewed,True,IPR037071,"Amyloidogenic glycoprotein, amyloid-beta pepti...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:4.10.230.10': 'Amyloidogenic glycoprot...,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 672, 'end': 711, 'dc-..."

Search in Batches

In [ ]:
queries: List[Union[str, Dict[str, Any]]] = [
    {
        "db": "InterPro",
        "modifiers": {},
        "filters": [{"type": "protein", "db": "reviewed", "value": "Q29537"}],
    },
    {
        "db": "InterPro",
        "modifiers": {},
        "filters": [{"type": "protein", "db": "reviewed", "value": "P05067"}],
    },
]
instance.fetch_batch(queries=queries, method="entry", pages_to_fetch=1, parse=True, format="dataframe")

Cache_key: {"db": "InterPro", "filters": [{"db": "reviewed", "type": "protein", "value": "Q29537"}], "modifiers": {}}_entry
Cache_key: {"db": "InterPro", "filters": [{"db": "reviewed", "type": "protein", "value": "P05067"}], "modifiers": {}}_entry
Cache_key: InterPro_{}_[{'type': 'protein', 'db': 'reviewed', 'value': 'Q29537'}]_entry
Fetching data from InterPro API with URL: https://www.ebi.ac.uk:443/interpro/api/entry/InterPro/protein/reviewed/Q29537/
Cache_key: InterPro_{}_[{'type': 'protein', 'db': 'reviewed', 'value': 'P05067'}]_entry
Fetching data from InterPro API with URL: https://www.ebi.ac.uk:443/interpro/api/entry/InterPro/protein/reviewed/P05067/

,accession,length,organism_id,protein_source_db,in_alphafold,interpro_accession,name,type,source_database,integrated,...,prosite,smart,prints,panther,cathgene3d,ssf,go_identifier,go_name,go_category,locations
0,q29537,381,9615,reviewed,True,IPR002117,p53 tumour suppressor family,family,interpro,None,...,None,None,{'PR00386': 'P53SUPPRESSR'},{'PTHR11447': 'CELLULAR TUMOR ANTIGEN P53'},None,None,"[GO:0003677, GO:0003700, GO:0006355, GO:000691...","[DNA binding, DNA-binding transcription factor...","[molecular_function, molecular_function, biolo...","{'fragments': [{'start': 3, 'end': 354, 'dc-st..."
1,q29537,381,9615,reviewed,True,IPR008967,"p53-like transcription factor, DNA-binding dom...",homologous_superfamily,interpro,None,...,None,None,None,None,None,{'SSF49417': 'p53-like transcription factors'},"[GO:0003700, GO:0006355]","[DNA-binding transcription factor activity, re...","[molecular_function, biological_process]","{'fragments': [{'start': 84, 'end': 275, 'dc-s..."
2,q29537,381,9615,reviewed,True,IPR010991,"p53, tetramerisation domain",domain,interpro,None,...,None,None,None,None,None,None,GO:0051262,protein tetramerization,biological_process,"{'fragments': [{'start': 307, 'end': 345, 'dc-..."
3,q29537,381,9615,reviewed,True,IPR011615,"p53, DNA-binding domain",domain,interpro,None,...,None,None,None,None,None,None,GO:0000976,transcription cis-regulatory region binding,molecular_function,"{'fragments': [{'start': 88, 'end': 277, 'dc-s..."
4,q29537,381,9615,reviewed,True,IPR012346,"p53/RUNT-type transcription factor, DNA-bindin...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:2.60.40.720': 'G3DSA:2.60.40.720'},None,"[GO:0003677, GO:0003700, GO:0006355, GO:0005634]","[DNA binding, DNA-binding transcription factor...","[molecular_function, molecular_function, biolo...","{'fragments': [{'start': 82, 'end': 282, 'dc-s..."
5,q29537,381,9615,reviewed,True,IPR013872,"p53, transactivation domain",domain,interpro,None,...,None,None,None,None,None,None,GO:0005515,protein binding,molecular_function,"{'fragments': [{'start': 6, 'end': 30, 'dc-sta..."
6,q29537,381,9615,reviewed,True,IPR036674,p53-like tetramerisation domain superfamily,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:4.10.170.10': 'p53-like tetramerisatio...,{'SSF47719': 'p53 tetramerization domain'},GO:0051262,protein tetramerization,biological_process,"{'fragments': [{'start': 307, 'end': 348, 'dc-..."
7,q29537,381,9615,reviewed,True,IPR057064,"p53, central conserved site",conserved_site,interpro,None,...,{'PS00348': 'p53 family signature'},None,None,None,None,None,None,None,None,"{'fragments': [{'start': 225, 'end': 237, 'dc-..."
8,p05067,770,9606,reviewed,True,IPR002223,Pancreatic trypsin inhibitor Kunitz domain,domain,interpro,None,...,None,{'SM00131': 'BPTI/Kunitz family of serine prot...,{'PR00759': 'BASICPTASE'},None,None,None,GO:0004867,serine-type endopeptidase inhibitor activity,molecular_function,"{'fragments': [{'start': 288, 'end': 342, 'dc-..."
9,p05067,770,9606,reviewed,True,IPR008154,"Amyloidogenic glycoprotein, extracellular",domain,interpro,None,...,None,{'SM00006': 'amyloid A4'},None,None,None,None,None,None,None,"{'fragments': [{'start': 24, 'end': 189, 'dc-s..."
10,p05067,770,9606,reviewed,True,IPR008155,Amyloidogenic glycoprotein,family,interpro,None,...,None,None,{'PR00203': 'AMYLOIDA4'},{'PTHR23103': 'ALZHEIMER'S DISEASE BETA-AMYLOI...,None,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 10, 'end': 770, 'dc-s..."
11,p05067,770,9606,reviewed,True,IPR011178,"Amyloidogenic glycoprotein, copper-binding",domain,interpro,None,...,None,None,None,None,None,None,GO:0046914,transition metal ion binding,molecular_function,"{'fragments': [{'start': 132, 'end': 188, 'dc-..."
12,p05067,770,9606,reviewed,True,IPR011993,PH-like domain superfamily,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:2.30.29.30': 'Pleckstrin-homology doma...,None,None,None,None,"{'fragments': [{'start': 742, 'end': 770, 'dc-..."
13,p05067,770,9606,reviewed,True,IPR013803,"Amyloidogenic glycoprotein, amyloid-beta peptide",domain,interpro,None,...,None,None,{'PR00204': 'BETAAMYLOID'},None,None,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 675, 'end': 713, 'dc-..."
14,p05067,770,9606,reviewed,True,IPR015849,"Amyloidogenic glycoprotein, heparin-binding",domain,interpro,None,...,None,None,None,None,None,None,GO:0008201,heparin binding,molecular_function,"{'fragments': [{'start': 31, 'end': 131, 'dc-s..."
15,p05067,770,9606,reviewed,True,IPR019543,Beta-amyloid precursor protein C-terminal,domain,interpro,None,...,None,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 716, 'end': 766, 'dc-..."
16,p05067,770,9606,reviewed,True,IPR019744,"Amyloidogenic glycoprotein, copper-binding dom...",conserved_site,interpro,None,...,{'PS00319': 'Amyloid precursor protein (APP) c...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 181, 'end': 188, 'dc-..."
17,p05067,770,9606,reviewed,True,IPR019745,"Amyloidogenic glycoprotein, intracellular doma...",conserved_site,interpro,None,...,{'PS00320': 'Amyloid precursor protein (APP) i...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 756, 'end': 763, 'dc-..."
18,p05067,770,9606,reviewed,True,IPR020901,"Proteinase inhibitor I2, Kunitz, conserved site",conserved_site,interpro,None,...,{'PS00280': 'Pancreatic trypsin inhibitor (Kun...,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 319, 'end': 337, 'dc-..."
19,p05067,770,9606,reviewed,True,IPR024329,"Amyloidogenic glycoprotein, E2 domain",domain,interpro,None,...,None,None,None,None,None,None,None,None,None,"{'fragments': [{'start': 367, 'end': 565, 'dc-..."
20,p05067,770,9606,reviewed,True,IPR036176,E2 domain superfamily,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:1.20.120.770': 'Amyloid precursor prot...,"{'SSF109843': 'CAPPD, an extracellular domain ...",None,None,None,"{'fragments': [{'start': 363, 'end': 580, 'dc-..."
21,p05067,770,9606,reviewed,True,IPR036454,"Amyloidogenic glycoprotein, heparin-binding do...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:3.90.570.10': 'Amyloidogenic glycoprot...,{'SSF56491': 'A heparin-binding domain'},GO:0008201,heparin binding,molecular_function,"{'fragments': [{'start': 17, 'end': 123, 'dc-s..."
22,p05067,770,9606,reviewed,True,IPR036669,"Amyloidogenic glycoprotein, copper-binding dom...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:3.30.1490.140': 'Amyloidogenic glycopr...,{'SSF89811': 'Amyloid beta a4 protein copper b...,GO:0046914,transition metal ion binding,molecular_function,"{'fragments': [{'start': 124, 'end': 189, 'dc-..."
23,p05067,770,9606,reviewed,True,IPR036880,Pancreatic trypsin inhibitor Kunitz domain sup...,homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:4.10.410.10': 'Pancreatic trypsin inhi...,{'SSF57362': 'BPTI-like'},GO:0004867,serine-type endopeptidase inhibitor activity,molecular_function,"{'fragments': [{'start': 279, 'end': 352, 'dc-..."
24,p05067,770,9606,reviewed,True,IPR037071,"Amyloidogenic glycoprotein, amyloid-beta pepti...",homologous_superfamily,interpro,None,...,None,None,None,None,{'G3DSA:4.10.230.10': 'Amyloidogenic glycoprot...,None,GO:0016020,membrane,cellular_component,"{'fragments': [{'start': 672, 'end': 711, 'dc-..."

## KEGG

### Importing the API

In [1]:
from bioseq_dl import KEGGInterface

### Instantiating the API

In [2]:
instance = KEGGInterface()

### Making a request

In [ ]:
response, _ = instance.fetch_single(
    query={"entries": ["hsa:10458", "ece:Z5100"]},
    method="get",
    format="dataframe",
    parse=True,
)
response

,entry,name,class,path_map,ko_pathway,rel_pathway,description,symbol,orthology,organism,pathway,network,brite,motif,dblinks,gene,compound,reference
0,10458 CDS T01001,(RefSeq) BAR/IMD domain containing adaptor pro...,None,None,None,None,None,"BAIAP2, BAP2, FLAF3, IRSP53, WAML",K05627 BAI1-associated protein 2,hsa Homo sapiens (human),"{'_value': 'hsa04517 IgSF CAM signaling', 'hs...",{'_value': 'nt06180 Pathogenic Escherichia co...,{'_value': 'KEGG Orthology (KO) [BR:hsa00001]'...,Pfam: IMD SH3_2 SH3_9 SH3_1 BAR Peptidase_Mx1 ...,NCBI-GeneID: 10458 NCBI-ProteinID: NP_00137205...,None,None,None
1,Z5100 CDS T00044,(GenBank) espF,None,None,None,None,None,espF,K12786 LEE-encoded effector EspF,ece Escherichia coli O157:H7 EDL933 (EHEC),ece05130 Pathogenic Escherichia coli infection,None,{'_value': 'KEGG Orthology (KO) [BR:ece00001]'...,Pfam: EspF,NCBI-ProteinID: AAG58814 UniProt: A0A9Q7EE73,None,None,None

In [ ]:
response, _ = instance.fetch_single(
    query={"entries": ["hsa:10458"], "db": "pathway"}, method="get", parse=True, format="json"
)
response

[{'entry': '10458             CDS       T01001',
  'name': '(RefSeq) BAR/IMD domain containing adaptor protein 2',
  'class': None,
  'path_map': None,
  'ko_pathway': None,
  'rel_pathway': None,
  'description': None,
  'symbol': 'BAIAP2, BAP2, FLAF3, IRSP53, WAML',
  'orthology': 'K05627  BAI1-associated protein 2',
  'organism': 'hsa  Homo sapiens (human)',
  'pathway': {'_value': 'hsa04517  IgSF CAM signaling',
   'hsa04520': ['Adherens junction'],
   'hsa04810': ['Regulation of actin cytoskeleton'],
   'hsa05130': ['Pathogenic Escherichia coli infection'],
   'hsa05135': ['Yersinia infection']},
  'network': {'_value': 'nt06180  Pathogenic Escherichia coli',
   'ELEMENT': ['N01094  Escherichia Eae/Tir/TccP to Actin signaling pathway']},
  'brite': {'_value': 'KEGG Orthology (KO) [BR:hsa00001]',
   '09130': ['Environmental Information Processing'],
   '09133': ['Signaling molecules and interaction'],
   '04517': ['IgSF CAM signaling'],
   '10458': ['(BAIAP2)',
    '(BAIAP2)',
    '(BAIAP2)',
    '(BAIAP2)',
    '(BAIAP2)',
    '(BAIAP2)',
    '(BAIAP2)'],
   '09140': ['Cellular Processes'],
   '09144': ['Cellular community - eukaryotes'],
   '04520': ['Adherens junction'],
   '09142': ['Cell motility'],
   '04810': ['Regulation of actin cytoskeleton'],
   '09160': ['Human Diseases'],
   '09171': ['Infectious disease: bacterial'],
   '05130': ['Pathogenic Escherichia coli infection'],
   '05135': ['Yersinia infection'],
   '09180': ['Brite Hierarchies'],
   '09182': ['Protein families: genetic information processing'],
   '04131': ['Membrane trafficking [BR:hsa04131]'],
   'Membrane': ['trafficking [BR:hsa04131]',
    'Endocytosis',
    'Bin/Amphiphysin/Rvs (BAR) family proteins',
    'I-BAR proteins']},
  'motif': 'Pfam: IMD SH3_2 SH3_9 SH3_1 BAR Peptidase_Mx1 NDC80_loop BAR_3',
  'dblinks': 'NCBI-GeneID: 10458 NCBI-ProteinID: NP_001372056 OMIM: 605475 HGNC: 947 Ensembl: ENSG00000175866 UniProt: Q9UQB8',
  'gene': None,
  'compound': None,
  'reference': None}]

Doing a pathway search

In [ ]:
response, _ = instance.fetch_single(
    query={"entries": ["path:hsa04517"]}, method="get", parse=True, format="json"
)
response

[{'entry': 'hsa04517                    Pathway',
  'name': 'IgSF CAM signaling - Homo sapiens (human)',
  'class': 'Environmental Information Processing; Signaling molecules and interaction',
  'path_map': 'hsa04517  IgSF CAM signaling',
  'ko_pathway': 'ko04517',
  'rel_pathway': {'_value': 'hsa04014  Ras signaling pathway',
   'hsa04064': ['NF-kappa B signaling pathway'],
   'hsa04360': ['Axon guidance'],
   'hsa04510': ['Focal adhesion'],
   'hsa04514': ['Cell adhesion molecule (CAM) interaction'],
   'hsa04520': ['Adherens junction'],
   'hsa04530': ['Tight junction'],
   'hsa04660': ['T cell receptor signaling pathway'],
   'hsa04670': ['Leukocyte transendothelial migration'],
   'hsa04810': ['Regulation of actin cytoskeleton']},
  'description': 'Immunoglobulin superfamily cell adhesion molecules (IgSF CAMs) are cell surface proteins that mediate calcium-independent adhesion via their Ig-like domains. These extracellular regions commonly form homophilic interactions with similar molecules on adjacent cells but can also bind heterophilically to various other molecular partners. Their intracellular tails associate with cytoskeletal and adaptor proteins, linking external adhesion events to intracellular signaling. Through these mechanisms, IgSF CAMs play key roles in both normal physiological regulation and disease processes such as cancer development.',
  'symbol': None,
  'orthology': None,
  'organism': 'Homo sapiens (human) [GN:hsa]',
  'pathway': None,
  'network': {'_value': 'nt06546  IgSF CAM signaling',
   'ELEMENT': ['N01933  NrCAM interactions'],
   'N01934': ['L1CAM interactions'],
   'N01935': ['NFASC interactions'],
   'N01936': ['CNTN1 interactions'],
   'N01937': ['CNTN2 interactions'],
   'N01938': ['MPZ interactions'],
   'N01939': ['Ganglioside-MAG signaling'],
   'N01940': ['Netrin-1 attractive signaling'],
   'N01941': ['Netrin-1 repulsive signaling'],
   'N01942': ['SLIT-ROBO signaling in neuron'],
   'N01943': ['SLIT-ROBO signaling in podocyte'],
   'N01944': ['SLIT-ROBO-SRGAP1 signaling in podocyte'],
   'N01945': ['SLIT-ROBO signaling in angiogenesis'],
   'N01946': ['PTPRF interactions'],
   'N01947': ['PTPRS interactions'],
   'N01948': ['PTPRD interactions'],
   'N01949': ['NECTIN1 interanctions'],
   'N01950': ['NECTIN2 interactions'],
   'N01951': ['NECTIN3 interactions'],
   'N01952': ['NECTIN4 interactions'],
   'N01953': ['NECL1 interactions'],
   'N01954': ['NECL2 interactions'],
   'N01955': ['CD96 interactions'],
   'N01956': ['JAM1 interactions'],
   'N01957': ['JAM2 interactions'],
   'N01958': ['JAM3 interactions'],
   'N01959': ['ESAM interactions'],
   'N01960': ['CLMP interactions'],
   'N01961': ['NPHS1/NEPH interactions'],
   'N01962': ['ICAM1 interactions'],
   'N01965': ['ICAM2 interactions'],
   'N01966': ['ICAM3 interactions'],
   'N01967': ['SLAMF interactions']},
  'brite': None,
  'motif': None,
  'dblinks': None,
  'gene': {'_value': '1000  CDH2; cadherin 2 [KO:K06736]',
   '10000': ['AKT3; AKT serine/threonine kinase 3 [KO:K04456] [EC:2.7.11.1]'],
   '10092': ['ARPC5; actin related protein 2/3 complex subunit 5 [KO:K05754]'],
   '10093': ['ARPC4; actin related protein 2/3 complex subunit 4 [KO:K05755]'],
   '10094': ['ARPC3; actin related protein 2/3 complex subunit 3 [KO:K05756]'],
   '10095': ['ARPC1B; actin related protein 2/3 complex subunit 1B [KO:K05757]'],
   '10096': ['ACTR3; actin related protein 3 [KO:K18584]'],
   '10097': ['ACTR2; actin related protein 2 [KO:K17260]'],
   '10109': ['ARPC2; actin related protein 2/3 complex subunit 2 [KO:K05758]'],
   '10225': ['CD96; CD96 molecule [KO:K06517]'],
   '10298': ['PAK4; p21 (RAC1) activated kinase 4 [KO:K05734] [EC:2.7.11.1]'],
   '10332': ['CLEC4M; C-type lectin domain family 4 member M [KO:K06563]'],
   '10376': ['TUBA1B; tubulin alpha 1b [KO:K07374]'],
   '10381': ['TUBB3; tubulin beta 3 class III [KO:K07375]'],
   '10382': ['TUBB4A; tubulin beta 4A class IVa [KO:K07375]'],
   '10383': ['TUBB4B; tubulin beta 4B class IVb [KO:K07375]'],
   '103910': ['MYL12B; myosin light chain 12B [KO:K12757]'],
   '10398': ['MYL9; myosin light chain 9 [KO:K12755]'],
   '10451': ['VAV3; vav guanine nucleotide exchange factor 3 [KO:K05730]'],
   '10458': ['BAIAP2; BAR/IMD domain containing adaptor protein 2 [KO:K05627]'],
   '10552': ['ARPC1A; actin related protein 2/3 complex subunit 1A [KO:K05757]'],
   '10580': ['SORBS1; sorbin and SH3 domain containing 1 [KO:K06086]'],
   '10627': ['MYL12A; myosin light chain 12A [KO:K12757]'],
   '10666': ['CD226; CD226 molecule [KO:K06567]'],
   '106821730': ['BUB1B-PAK6; BUB1B-PAK6 readthrough [KO:K05735] [EC:2.7.11.1]'],
   '110117499': ['P3R3URF-PIK3R3; P3R3URF-PIK3R3 readthrough [KO:K02649]'],
   '11141': ['IL1RAPL1; interleukin 1 receptor accessory protein like 1 [KO:K05170]'],
   '112714': ['TUBA3E; tubulin alpha 3e [KO:K07374]'],
   '113457': ['TUBA3D; tubulin alpha 3d [KO:K07374]'],
   '114798': ['SLITRK1; SLIT and NTRK like family member 1 [KO:K25832]'],
   '114836': ['SLAMF6; SLAM family member 6 [KO:K16852]'],
   '117157': ['SH2D1B; SH2 domain containing 1B [KO:K07989]'],
   '117178': ['SSX2IP; SSX family member 2 interacting protein [KO:K06085]'],
   '120425': ['JAML; junction adhesion molecule like [KO:K28137]'],
   '124908013': ['[KO:K07375]'],
   '124908015': ['[KO:K07375]'],
   '124908041': ['[KO:K07375]'],
   '1272': ['CNTN1; contactin 1 [KO:K06759]'],
   '137970': ['UNC5D; unc-5 netrin receptor D [KO:K07521]'],
   '139065': ['SLITRK4; SLIT and NTRK like family member 4 [KO:K25835]'],
   '140465': ['MYL6B; myosin light chain 6B [KO:K12751]'],
   '140735': ['DYNLL2; dynein light chain LC8-type 2 [KO:K10418]'],
   '1432': ['MAPK14; mitogen-activated protein kinase 14 [KO:K04441] [EC:2.7.11.24]'],
   '1445': ['CSK; C-terminal Src kinase [KO:K05728] [EC:2.7.10.4]'],
   '145581': ['LRFN5; leucine rich repeat and fibronectin type III domain containing 5 [KO:K16358]'],
   '1499': ['CTNNB1; catenin beta 1 [KO:K02105]'],
   '150084': ['IGSF5; immunoglobulin superfamily member 5 [KO:K06786]'],
   '1525': ['CXADR; CXADR cell adhesion molecule [KO:K06788]'],
   '1630': ['DCC; DCC netrin 1 receptor [KO:K06765]'],
   '1796': ['DOK1; docking protein 1 [KO:K14752]'],
   '199731': ['CADM4; cell adhesion molecule 4 [KO:K06783]'],
   '201633': ['TIGIT; T cell immunoreceptor with Ig and ITIM domains [KO:K16350]'],
   '203068': ['TUBB; tubulin beta class I [KO:K07375]'],
   '2036': ['EPB41L1; erythrocyte membrane protein band 4.1 like 1 [KO:K23961]'],
   '2037': ['EPB41L2; erythrocyte membrane protein band 4.1 like 2 [KO:K23961]'],
   '207': ['AKT1; AKT serine/threonine kinase 1 [KO:K04456] [EC:2.7.11.1]'],
   '208': ['AKT2; AKT serine/threonine kinase 2 [KO:K04456] [EC:2.7.11.1]'],
   '219699': ['UNC5B; unc-5 netrin receptor B [KO:K07521]'],
   '2243': ['FGA; fibrinogen alpha chain [KO:K03903]'],
   '2244': ['FGB; fibrinogen beta chain [KO:K03904]'],
   '2260': ['FGFR1; fibroblast growth factor receptor 1 [KO:K04362] [EC:2.7.10.1]'],
   '2266': ['FGG; fibrinogen gamma chain [KO:K03905]'],
   '22829': ['NLGN4Y; neuroligin 4 Y-linked [KO:K07378]'],
   '22865': ['SLITRK3; SLIT and NTRK like family member 3 [KO:K25834]'],
   '22871': ['NLGN1; neuroligin 1 [KO:K07378]'],
   '22999': ['RIMS1; regulating synaptic membrane exocytosis 1 [KO:K15291]'],
   '2308': ['FOXO1; forkhead box O1 [KO:K07201]'],
   '23085': ['ERC1; ELKS/RAB6-interacting/CAST family member 1 [KO:K16072]'],
   '23114': ['NFASC; neurofascin [KO:K06757]'],
   '23136': ['EPB41L3; erythrocyte membrane protein band 4.1 like 3 [KO:K23961]'],
   '23380': ['SRGAP2; SLIT-ROBO Rho GTPase activating protein 2 [KO:K07526]'],
   '23426': ['GRIP1; glutamate receptor interacting protein 1 [KO:K20251]'],
   '23607': ['CD2AP; CD2 associated protein [KO:K13738]'],
   '23705': ['CADM1; cell adhesion molecule 1 [KO:K06781]'],
   '25': ['ABL1; ABL proto-oncogene 1, non-receptor tyrosine kinase [KO:K06619] [EC:2.7.10.2]'],
   '2534': ['FYN; FYN proto-oncogene, Src family tyrosine kinase [KO:K05703] [EC:2.7.10.2]'],
   '253559': ['CADM2; cell adhesion molecule 2 [KO:K06782]'],
   '25945': ['NECTIN3; nectin cell adhesion molecule 3 [KO:K06592]'],
   '260334': ['TUBB8B; tubulin beta 8B [KO:K07375]'],
   '26047': ['CNTNAP2; contactin associated protein 2 [KO:K07380]'],
   '26050': ['SLITRK5; SLIT and NTRK like family member 5 [KO:K25836]'],
   '26280': ['IL1RAPL2; interleukin 1 receptor accessory protein like 2 [KO:K05170]'],
   '287': ['ANK2; ankyrin 2 [KO:K09255]'],
   '288': ['ANK3; ankyrin 3 [KO:K09259]'],
   '2885': ['GRB2; growth factor receptor bound protein 2 [KO:K04364]'],
   '28964': ['GIT1; GIT ArfGAP 1 [KO:K05737]'],
   '2932': ['GSK3B; glycogen synthase kinase 3 beta [KO:K03083] [EC:2.7.11.26]'],
   '30835': ['CD209; CD209 molecule [KO:K06563]'],
   '3383': ['ICAM1; intercellular adhesion molecule 1 [KO:K06490]'],
   '3384': ['ICAM2; intercellular adhesion molecule 2 [KO:K06523]'],
   '3385': ['ICAM3; intercellular adhesion molecule 3 [KO:K06486]'],
   '340156': ['MYLK4; myosin light chain kinase family member 4 [KO:K00907] [EC:2.7.11.18]'],
   '342035': ['GLDN; gliomedin [KO:K16364]'],
   '347688': ['TUBB8; tubulin beta 8 class VIII [KO:K07375]'],
   '347733': ['TUBB2B; tubulin beta 2B class IIb [KO:K07375]'],
   '351': ['APP; amyloid beta precursor protein [KO:K04520]'],
   '3556': ['IL1RAP; interleukin 1 receptor accessory protein [KO:K04723]'],
   '3635': ['INPP5D; inositol polyphosphate-5-phosphatase D [KO:K03084] [EC:3.1.3.86]'],
   '3676': ['ITGA4; integrin subunit alpha 4 [KO:K06483]'],
   '3678': ['ITGA5; integrin subunit alpha 5 [KO:K06484]'],
   '3683': ['ITGAL; integrin subunit alpha L [KO:K05718]'],
   '3684': ['ITGAM; integrin subunit alpha M [KO:K06461]'],
   '3687': ['ITGAX; integrin subunit alpha X [KO:K06462]'],
   '3688': ['ITGB1; integrin subunit beta 1 [KO:K05719]'],
   '3689': ['ITGB2; integrin subunit beta 2 [KO:K06464]'],
   '3690': ['ITGB3; integrin subunit beta 3 [KO:K06493]'],
   '3736': ['KCNA1; potassium voltage-gated channel subfamily A member 1 [KO:K04874]'],
   '3737': ['KCNA2; potassium voltage-gated channel subfamily A member 2 [KO:K04875]'],
   '3739': ['KCNA4; potassium voltage-gated channel subfamily A member 4 [KO:K04877]'],
   '3742': ['KCNA6; potassium voltage-gated channel subfamily A member 6 [KO:K04879]'],
   '3785': ['KCNQ2; potassium voltage-gated channel subfamily Q member 2 [KO:K04927]'],
   '3786': ['KCNQ3; potassium voltage-gated channel subfamily Q member 3 [KO:K04928]'],
   '3791': ['KDR; kinase insert domain receptor [KO:K05098] [EC:2.7.10.1]'],
   '382': ['ARF6; ARF GTPase 6 [KO:K07941]'],
   '387': ['RHOA; ras homolog family member A [KO:K04513]'],
   '3897': ['L1CAM; L1 cell adhesion molecule [KO:K06550]'],
   '3932': ['LCK; LCK proto-oncogene, Src family tyrosine kinase [KO:K05856] [EC:2.7.10.2]'],
   '3937': ['LCP2; lymphocyte cytosolic protein 2 [KO:K07361]'],
   '4008': ['LMO7; LIM domain 7 [KO:K06084]'],
   '4063': ['LY9; lymphocyte antigen 9 [KO:K06570]'],
   '4067': ['LYN; LYN proto-oncogene, Src family tyrosine kinase [KO:K05854] [EC:2.7.10.2]'],
   '4068': ['SH2D1A; SH2 domain containing 1A [KO:K07990]'],
   '4099': ['MAG; myelin associated glycoprotein [KO:K06771]'],
   '4133': ['MAP2; microtubule associated protein 2 [KO:K10430]'],
   '4155': ['MBP; myelin basic protein [KO:K17269]'],
   '4301': ['AFDN; afadin, adherens junction formation factor [KO:K05702]'],
   '4356': ['MPP3; MAGUK p55 scaffold protein 3 [KO:K24049]'],
   '4359': ['MPZ; myelin protein zero [KO:K06770]'],
   '4478': ['MSN; moesin [KO:K05763]'],
   '4627': ['MYH9; myosin heavy chain 9 [KO:K10352]'],
   '4628': ['MYH10; myosin heavy chain 10 [KO:K10352]'],
   '4629': ['MYH11; myosin heavy chain 11 [KO:K10352]'],
   '4637': ['MYL6; myosin light chain 6 [KO:K12751]'],
   '4638': ['MYLK; myosin light chain kinase [KO:K00907] [EC:2.7.11.18]'],
   '4684': ['NCAM1; neural cell adhesion molecule 1 [KO:K06491]'],
   '4685': ['NCAM2; neural cell adhesion molecule 2 [KO:K06491]'],
   '4690': ['NCK1; NCK adaptor protein 1 [KO:K07365]'],
   '4868': ['NPHS1; NPHS1 adhesion molecule, nephrin [KO:K24496]'],
   '4897': ['NRCAM; neuronal cell adhesion molecule [KO:K06756]'],
   '4916': ['NTRK3; neurotrophic receptor tyrosine kinase 3 [KO:K05101] [EC:2.7.10.1]'],
   '5058': ['PAK1; p21 (RAC1) activated kinase 1 [KO:K04409] [EC:2.7.11.1]'],
   '5062': ['PAK2; p21 (RAC1) activated kinase 2 [KO:K04410] [EC:2.7.11.1]'],
   '5063': ['PAK3; p21 (RAC1) activated kinase 3 [KO:K05733] [EC:2.7.11.1]'],
   '50848': ['F11R; F11 receptor [KO:K06089]'],
   '50855': ['PARD6A; par-6 family cell polarity regulator alpha [KO:K06093]'],
   '51332': ['SPTBN5; spectrin beta, non-erythrocytic 5 [KO:K06115]'],
   '51678': ['PALS2; protein associated with LIN7 2, MAGUK p55 family member [KO:K28619]'],
   '5170': ['PDPK1; 3-phosphoinositide dependent protein kinase 1 [KO:K06276] [EC:2.7.11.1]'],
   '51735': ['RAPGEF6; Rap guanine nucleotide exchange factor 6 [KO:K08020]'],
   '51744': ['CD244; CD244 molecule [KO:K06582]'],
   '51807': ['TUBA8; tubulin alpha 8 [KO:K07374]'],
   '5290': ['PIK3CA; phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha [KO:K00922] [EC:2.7.1.153]'],
   '5291': ['PIK3CB; phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit beta [KO:K00922] [EC:2.7.1.153]'],
   '5293': ['PIK3CD; phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit delta [KO:K00922] [EC:2.7.1.153]'],
   '5295': ['PIK3R1; phosphoinositide-3-kinase regulatory subunit 1 [KO:K02649]'],
   '5296': ['PIK3R2; phosphoinositide-3-kinase regulatory subunit 2 [KO:K02649]'],
   '5335': ['PLCG1; phospholipase C gamma 1 [KO:K01116] [EC:3.1.4.11]'],
   '5336': ['PLCG2; phospholipase C gamma 2 [KO:K05859] [EC:3.1.4.11]'],
   '5361': ['PLXNA1; plexin A1 [KO:K06820]'],
   '5362': ['PLXNA2; plexin A2 [KO:K06820]'],
   '5375': ['PMP2; peripheral myelin protein 2 [KO:K24977]'],
   '5376': ['PMP22; peripheral myelin protein 22 [KO:K19289]'],
   '54413': ['NLGN3; neuroligin 3 [KO:K07378]'],
   '54538': ['ROBO4; roundabout guidance receptor 4 [KO:K06784]'],
   '55243': ['KIRREL1; kirre like nephrin family adhesion molecule 1 [KO:K25874]'],
   '55558': ['PLXNA3; plexin A3 [KO:K06820]'],
   '5578': ['PRKCA; protein kinase C alpha [KO:K02677] [EC:2.7.11.13]'],
   '5579': ['PRKCB; protein kinase C beta [KO:K19662] [EC:2.7.11.13]'],
   '5582': ['PRKCG; protein kinase C gamma [KO:K19663] [EC:2.7.11.13]'],
   '5584': ['PRKCI; protein kinase C iota [KO:K06069] [EC:2.7.11.13]'],
   '5588': ['PRKCQ; protein kinase C theta [KO:K18052] [EC:2.7.11.13]'],
   '5594': ['MAPK1; mitogen-activated protein kinase 1 [KO:K04371] [EC:2.7.11.24]'],
   '5595': ['MAPK3; mitogen-activated protein kinase 3 [KO:K04371] [EC:2.7.11.24]'],
   '5599': ['MAPK8; mitogen-activated protein kinase 8 [KO:K04440] [EC:2.7.11.24]'],
   '5600': ['MAPK11; mitogen-activated protein kinase 11 [KO:K04441] [EC:2.7.11.24]'],
   '5601': ['MAPK9; mitogen-activated protein kinase 9 [KO:K04440] [EC:2.7.11.24]'],
   '5602': ['MAPK10; mitogen-activated protein kinase 10 [KO:K04440] [EC:2.7.11.24]'],
   '5603': ['MAPK13; mitogen-activated protein kinase 13 [KO:K04441] [EC:2.7.11.24]'],
   '5604': ['MAP2K1; mitogen-activated protein kinase kinase 1 [KO:K04368] [EC:2.7.12.2]'],
   '5605': ['MAP2K2; mitogen-activated protein kinase kinase 2 [KO:K04369] [EC:2.7.12.2]'],
   '56253': ['CRTAM; cytotoxic and regulatory T cell molecule [KO:K16361]'],
   '56288': ['PARD3; par-3 family cell polarity regulator [KO:K04237]'],
   '56924': ['PAK6; p21 (RAC1) activated kinase 6 [KO:K05735] [EC:2.7.11.1]'],
   '57144': ['PAK5; p21 (RAC1) activated kinase 5 [KO:K05736] [EC:2.7.11.1]'],
   '57180': ['ACTR3B; actin related protein 3B [KO:K18584]'],
   '5747': ['PTK2; protein tyrosine kinase 2 [KO:K05725] [EC:2.7.10.2]'],
   '57502': ['NLGN4X; neuroligin 4 X-linked [KO:K07378]'],
   '57513': ['CASKIN2; CASK interacting protein 2 [KO:K21952]'],
   '57522': ['SRGAP1; SLIT-ROBO Rho GTPase activating protein 1 [KO:K07526]'],
   '57524': ['CASKIN1; CASK interacting protein 1 [KO:K21952]'],
   '57555': ['NLGN2; neuroligin 2 [KO:K07378]'],
   '57689': ['LRRC4C; leucine rich repeat containing 4C [KO:K07523]'],
   '57731': ['SPTBN4; spectrin beta, non-erythrocytic 4 [KO:K06115]'],
   '5777': ['PTPN6; protein tyrosine phosphatase non-receptor type 6 [KO:K05697] [EC:3.1.3.48]'],
   '5781': ['PTPN11; protein tyrosine phosphatase non-receptor type 11 [KO:K07293] [EC:3.1.3.48]'],
   '57823': ['SLAMF7; SLAM family member 7 [KO:K06733]'],
   '57863': ['CADM3; cell adhesion molecule 3 [KO:K06780]'],
   '5789': ['PTPRD; protein tyrosine phosphatase receptor type D [KO:K06777] [EC:3.1.3.48]'],
   '5792': ['PTPRF; protein tyrosine phosphatase receptor type F [KO:K05695] [EC:3.1.3.48]'],
   '5802': ['PTPRS; protein tyrosine phosphatase receptor type S [KO:K06778] [EC:3.1.3.48]'],
   '5803': ['PTPRZ1; protein tyrosine phosphatase receptor type Z1 [KO:K08114] [EC:3.1.3.48]'],
   '5817': ['PVR; PVR cell adhesion molecule [KO:K06539]'],
   '5818': ['NECTIN1; nectin cell adhesion molecule 1 [KO:K06081]'],
   '5819': ['NECTIN2; nectin cell adhesion molecule 2 [KO:K06531]'],
   '5829': ['PXN; paxillin [KO:K05760]'],
   '58494': ['JAM2; junctional adhesion molecule 2 [KO:K06735]'],
   '5879': ['RAC1; Rac family small GTPase 1 [KO:K04392]'],
   '5906': ['RAP1A; RAP1A, member of RAS oncogene family [KO:K04353]'],
   '5908': ['RAP1B; RAP1B, member of RAS oncogene family [KO:K07836]'],
   '5921': ['RASA1; RAS p21 protein activator 1 [KO:K04352]'],
   '5962': ['RDX; radixin [KO:K05762]'],
   '60': ['ACTB; actin beta [KO:K05692]'],
   '6091': ['ROBO1; roundabout guidance receptor 1 [KO:K06753]'],
   '6092': ['ROBO2; roundabout guidance receptor 2 [KO:K06754]'],
   '6300': ['MAPK12; mitogen-activated protein kinase 12 [KO:K04441] [EC:2.7.11.24]'],
   '6334': ['SCN8A; sodium voltage-gated channel alpha subunit 8 [KO:K04840]'],
   '64221': ['ROBO3; roundabout guidance receptor 3 [KO:K06755]'],
   '6504': ['SLAMF1; signaling lymphocytic activation molecule family member 1 [KO:K06536]'],
   '653857': ['ACTR3C; actin related protein 3C [KO:K18584]'],
   '6585': ['SLIT1; slit guidance ligand 1 [KO:K06838]'],
   '6586': ['SLIT3; slit guidance ligand 3 [KO:K06850]'],
   '6709': ['SPTAN1; spectrin alpha, non-erythrocytic 1 [KO:K06114]'],
   '6711': ['SPTBN1; spectrin beta, non-erythrocytic 1 [KO:K06115]'],
   '6712': ['SPTBN2; spectrin beta, non-erythrocytic 2 [KO:K23932]'],
   '6714': ['SRC; SRC proto-oncogene, non-receptor tyrosine kinase [KO:K05704] [EC:2.7.10.2]'],
   '6900': ['CNTN2; contactin 2 [KO:K06760]'],
   '7082': ['TJP1; tight junction protein 1 [KO:K05701]'],
   '71': ['ACTG1; actin gamma 1 [KO:K05692]'],
   '7189': ['TRAF6; TNF receptor associated factor 6 [KO:K03175] [EC:2.3.2.27]'],
   '7204': ['TRIO; trio Rho guanine nucleotide exchange factor [KO:K08810] [EC:2.7.11.1]'],
   '7225': ['TRPC6; transient receptor potential cation channel subfamily C member 6 [KO:K04969]'],
   '7277': ['TUBA4A; tubulin alpha 4a [KO:K07374]'],
   '7278': ['TUBA3C; tubulin alpha 3c [KO:K07374]'],
   '7280': ['TUBB2A; tubulin beta 2A class IIa [KO:K07375]'],
   '7409': ['VAV1; vav guanine nucleotide exchange factor 1 [KO:K05730]'],
   '7410': ['VAV2; vav guanine nucleotide exchange factor 2 [KO:K05730]'],
   '7414': ['VCL; vinculin [KO:K05700]'],
   '7430': ['EZR; ezrin [KO:K08007]'],
   '7827': ['NPHS2; NPHS2 stomatin family member, podocin [KO:K18268]'],
   '7846': ['TUBA1A; tubulin alpha 1a [KO:K07374]'],
   '78999': ['LRFN4; leucine rich repeat and fibronectin type III domain containing 4 [KO:K16357]'],
   '79784': ['MYH14; myosin heavy chain 14 [KO:K10352]'],
   '79827': ['CLMP; CXADR like cell adhesion molecule [KO:K06789]'],
   '79861': ['TUBAL3; tubulin alpha like 3 [KO:K07374]'],
   '80059': ['LRRTM4; leucine rich repeat transmembrane neuronal 4 [KO:K28622]'],
   '80852': ['GRIP2; glutamate receptor interacting protein 2 [KO:K20251]'],

In [ ]:
instance.fetch_single(
    query={"entries": ["hsa:10458", "ece:Z5100"]}, method="pathways", parse=True, format="dataframe"
)[0]

,ENTRY,NAME,DESCRIPTION,CLASS,PATHWAY_MAP,NETWORK,ORGANISM,GENE,COMPOUND,REFERENCE,REL_PATHWAY,KO_PATHWAY,DRUG,DBLINKS,DISEASE,MODULE
0,hsa04517 Pathway,IgSF CAM signaling - Homo sapiens (human),Immunoglobulin superfamily cell adhesion molec...,Environmental Information Processing; Signalin...,hsa04517 IgSF CAM signaling,"{'_value': 'nt06546 IgSF CAM signaling', 'ELE...",Homo sapiens (human) [GN:hsa],{'_value': '1000 CDH2; cadherin 2 [KO:K06736]...,"{'_value': 'C00076 Calcium cation', 'C01245':...",{'_value': [{'_value': [{'_value': [{'_value':...,"{'_value': 'hsa04014 Ras signaling pathway', ...",ko04517,NaN,NaN,NaN,NaN
1,hsa04520 Pathway,Adherens junction - Homo sapiens (human),"Cell-cell adherens junctions (AJs), the most c...",Cellular Processes; Cellular community - eukar...,hsa04520 Adherens junction,NaN,Homo sapiens (human) [GN:hsa],{'_value': '1003 CDH5; cadherin 5 [KO:K06533]...,NaN,{'_value': [{'_value': [{'_value': [{'_value':...,"{'_value': 'hsa04010 MAPK signaling pathway',...",ko04520,"{'_value': 'D05716 Repifermin (USAN/INN)', 'D...",GO: 0005912,NaN,NaN
2,hsa04810 Pathway,Regulation of actin cytoskeleton - Homo sapien...,NaN,Cellular Processes; Cell motility,hsa04810 Regulation of actin cytoskeleton,{'_value': 'nt06167 Human cytomegalovirus (HC...,Homo sapiens (human) [GN:hsa],{'_value': '10000 AKT3; AKT serine/threonine ...,{'_value': 'C00681 1-Acyl-sn-glycerol 3-phosp...,{'_value': [{'_value': [{'_value': [{'_value':...,"{'_value': 'hsa04010 MAPK signaling pathway',...",ko04810,{'_value': 'D01175 Carpronium chloride (JAN/I...,GO: 0030036,NaN,NaN
3,hsa05130 Pathway,Pathogenic Escherichia coli infection - Homo s...,Enteropathogenic E. coli (EPEC) and enterohemo...,Human Diseases; Infectious disease: bacterial,hsa05130 Pathogenic Escherichia coli infection,{'_value': 'nt06180 Pathogenic Escherichia co...,Homo sapiens (human) [GN:hsa],{'_value': '10006 ABI1; abl interactor 1 [KO:...,"{'_value': 'C00338 Lipopolysaccharide', 'C003...",{'_value': [{'_value': [{'_value': [{'_value':...,{'_value': 'hsa04064 NF-kappa B signaling pat...,ko05130,NaN,NaN,{'_value': 'H00277 Enterohemorrhagic Escheric...,NaN
4,hsa05135 Pathway,Yersinia infection - Homo sapiens (human),Pathogenic Yersinia injects virulent Yersinia ...,Human Diseases; Infectious disease: bacterial,hsa05135 Yersinia infection,"{'_value': 'nt06183 Yersinia', 'nt06517': ['T...",Homo sapiens (human) [GN:hsa],{'_value': '10000 AKT3; AKT serine/threonine ...,"{'_value': 'C00076 Calcium cation', 'C00338':...",{'_value': [{'_value': [{'_value': [{'_value':...,"{'_value': 'hsa04510 Focal adhesion', 'hsa046...",ko05135,NaN,NaN,H00298 Yersiniosis,NaN
5,ece05130 Pathway,Pathogenic Escherichia coli infection - Escher...,Enteropathogenic E. coli (EPEC) and enterohemo...,Human Diseases; Infectious disease: bacterial,ece05130 Pathogenic Escherichia coli infection,NaN,Escherichia coli O157:H7 EDL933 (EHEC) [GN:ece],"{'_value': 'Z0985 [KO:K23657]', 'Z0986': ['[K...","{'_value': 'C00338 Lipopolysaccharide', 'C003...",{'_value': [{'_value': [{'_value': [{'_value':...,"{'_value': 'ece02040 Flagellar assembly', 'ec...",ko05130,NaN,NaN,{'_value': 'H00277 Enterohemorrhagic Escheric...,{'_value': 'ece_M00363 EHEC pathogenicity sig...

## PathwayCommons

### Importing the API

In [1]:
from bioseq_dl import PathwayCommonsInterface

### Instantiating the API

In [2]:
instance = PathwayCommonsInterface()

### Making a Request

In [3]:
instance.fetch(query={"q": "TYW5", "organism": ["9606"], "datasource": ["reactome"]}, method="top_pathways")

[]

In [ ]:
response, _ = instance.fetch_single(
    query={"q": "TYW5", "organism": ["9606"], "datasource": ["reactome", "uniprot"]},
    method="top_pathways",
    parse=False,
    format="json",
)
response

[]

In [ ]:
response, _ = instance.fetch_single(
    query={"uri": ["R-HSA-75876"], "pattern": ["interacts-with", "used-to-produce"]},
    method="fetch",
    parse=True,
    format="dataframe",
)
response

Cache_key: ['R-HSA-75876']_['interacts-with', 'used-to-produce']_fetch
Prepared request: https://www.pathwaycommons.org/pc2/v2/fetch
Fetching data with parameters: {'uri': ['R-HSA-75876'], 'format': 'jsonld', 'pattern': ['interacts-with', 'used-to-produce'], 'subpw': False}

Empty DataFrame
Columns: []
Index: [0]

In [ ]:
response, _ = instance.fetch_single(
    query={"uri": ["R-ALL-444824"], "pattern": ["interacts-with", "used-to-produce"]},
    method="fetch",
    parse=True,
    format="dataframe",
)
response

,id,name,db,cellular_location,chemical_formula,comment,component,component_stoichiometry,data_source,display_name,...,sequence_interval_begin,sequence_interval_end,sequence_position,standard_name,stoichiometric_coefficient,structure,structure_data,structure_format,term,xref
0,CHEBI:15551,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,CHEBI:15552,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,CHEBI:15555,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CHEBI:16335,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,CHEBI:18397,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822,Q9P1P5,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1823,Q9P2W3,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1824,Q9UBI6,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1825,Q9UK08,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1826,Q9Y5Y3,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
response, _ = instance.fetch_single(
    query={"q": "APP", "organism": ["9606"], "datasource": ["reactome", "uniprot"]},
    method="top_pathways",
    parse=True,
    format="dataframe",
)
response

,uri,biopax_class,name,data_source,organism,pathway,excerpt,num_participants,num_processes
0,http://bioregistry.io/reactome:R-HSA-392499,Pathway,Metabolism of proteins,pc14:reactome,http://bioregistry.io/ncbitaxon:9606,[],None,0,9
1,http://bioregistry.io/reactome:R-HSA-162582,Pathway,Signaling Pathways,pc14:reactome,http://bioregistry.io/ncbitaxon:9606,[],None,0,17

In [ ]:
response, _ = instance.fetch_single(
    query={
        "source": ["Q16602"],
        "limit": 1,
        "format": "jsonld",
        "organism": ["9606"],
        "datasource": ["reactome"],
        "pattern": ["interacts-with", "used-to-produce"],
        "subpw": True,
        "direction": "undirected",
    },
    method="neighborhood",
    parse=True,
    format="dataframe",
)
response

,id,name,db,cellular_location,chemical_formula,comment,component,component_stoichiometry,control_type,controlled,...,standard_name,stoichiometric_coefficient,structure,structure_data,structure_format,term,title,url,xref,year
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CHEBI:10100,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,CHEBI:15354,None,chebi,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6454,Q9UNW8,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6455,Q9Y271,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6456,Q9Y287,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6457,Q9Y5X5,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6458,Q9Y5Y3,None,uniprot,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

## PDB

### Importing the API

In [1]:
from bioseq_dl import PDBInterface

### Instantiating the API

In [2]:
instance = PDBInterface(download_structures=True)

### Making a request

Note that by setting download_structures=True, the structure files will be downloaded to the structures directory.

In [ ]:
response, _ = instance.fetch_single(query="4HHB", method="entry", parse=True, format="dataframe")
response

2025-11-28 12:36:41 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 4HHB in pdb format...
2025-11-28 12:36:41 | INFO     | bioseq_dl.interfaces.pdb | Structure for 4HHB already exists in pdb format.

,rcsb_id,model_provenance,branched_molecular_weight_minimum,resolution_combined,experimental_method,diffrn_resolution_high
0,4HHB,None,None,1.74,X-ray,1.74

In [ ]:
response, _ = instance.fetch_batch(
    queries=["4HHB", "1A8I", "1A8J", "1A8K", "1A8L", "1A8M"], method="entry", parse=True, format="dataframe"
)
response.head(5)

2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8I in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8J in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8K in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8L in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Downloading 1A8I in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8M in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Downloading 1A8J in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Downloading 1A8K in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Downloading 1A8L in pdb format...
2025-11-28 12:37:35 | INFO     | bioseq_dl.interfaces.pdb | Downloading 1A8M in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 4HHB in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 4HHB already exists in pdb format.
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8I in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 1A8I already exists in pdb format.
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8J in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 1A8J already exists in pdb format.
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8K in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 1A8K already exists in pdb format.
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8L in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 1A8L already exists in pdb format.
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Fetching structure for 1A8M in pdb format...
2025-11-28 12:37:48 | INFO     | bioseq_dl.interfaces.pdb | Structure for 1A8M already exists in pdb format.

,rcsb_id,model_provenance,branched_molecular_weight_minimum,resolution_combined,experimental_method,diffrn_resolution_high
0,4HHB,None,None,1.74,X-ray,1.74
1,1A8I,None,None,1.78,X-ray,1.78
2,1A8J,None,None,2.70,X-ray,2.70
3,1A8K,None,None,2.00,X-ray,2.00
4,1A8L,None,None,1.90,X-ray,1.90

## Pride

### Importing the API

In [7]:
from bioseq_dl import PrideInterface

### Instantiating the API

In [8]:
instance = PrideInterface()

### Making a request

In [ ]:
response, _ = instance.fetch_single(
    query={
        "keyword": "cancer",
    },
    method="search",
    option="projects",
    parse=True,
    format="dataframe",
)
response

,accession,title,additional_attributes,project_description,sample_processing_protocol,data_processing_protocol,project_tags,keywords,doi,submission_type,...,experiment_types,quantification_methods,countries,sample_attributes,organisms,organism_parts,diseases,references,identified_ptm_strings,total_file_downloads
0,PXD070903,AR RIME in Human Prostate Cancer Cells,None,"BPTF, the scaffolding subunit of the nucleosom...",RIME was performed as previously described wit...,All mass spectra from were analyzed with MaxQu...,[],"[Ar, Human prostate cancer cell, Rv1]",,PARTIAL,...,Affinity purification coupled with mass spectr...,[],None,"[prostate adenocarcinoma, cell culture, Homo s...",Homo sapiens (human),None,"[Prostate adenocarcinoma, Castration-resistant...",[],None,None
1,PXD070833,Label-free proteome analysis of pancreatic can...,None,The glycolytic inhibitor 2-deoxy-d-glucose (2D...,Label-free proteome analysis 1. Sample prepara...,1. Protein identification and semi-quantitativ...,[],"[Human, Cell line, Pancreatic cancer, Label-fr...",,PARTIAL,...,Data-dependent acquisition,Spectrum counting,None,"[cell culture, Homo sapiens (Human), epithelia...",Homo sapiens (human),None,Pancreatic ductal adenocarcinoma,"Ishino K, Kudo M, Peng WX, Kure S, Kawahara K,...",None,None
2,PXD070770,Chemical-proteomics profiling of reactive cyst...,None,This project investigates reactive cysteine re...,HEK293A cells were treated with DMSO or cystei...,Raw MS/MS data were processed by the Taplin Ma...,[],"[Reactive cysteines, Autopalmitoylation, Drugg...",10.6019/PXD070770,COMPLETE,...,Bottom-up proteomics,[],None,Homo sapiens (Human),Homo sapiens (human),None,[],null--pubMed:0--doi: 10.6019/PXD070770,None,None
3,PXD070494,Pre- and Post- NACT ovarian cancer,None,Samples from 22 ovarian cancer patients before...,Tissue was cryopulverized in tissueTUBES (Cova...,The experimental samples were acquired on a ti...,[],"[Neoadjuvant chemotherapy, Ovarian cancer]",,PARTIAL,...,diaPASEF,[],None,"[Homo sapiens (Human), ovary cancer cell]",Homo sapiens (human),None,[],"Valentine MC, Mullen MM, Kotnik EN, Powell MA,...",None,None
4,PXD070432,A Molecular Clamp Targeting the TOE1:Sm Comple...,None,Small nuclear RNAs (snRNAs) are required for t...,Approximately 1 × 10^7 parental MCC142 cells w...,The raw data was processed in IP2 using standa...,[],"[Human, Toe1, Cancer, Snrna]",,PARTIAL,...,Bottom-up proteomics,[],None,"[cell culture, Homo sapiens (Human)]",Homo sapiens (human),None,[],[],None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PXD065163,Identification of a Highly Cooperative PROTAC ...,None,Kirsten rat sarcoma viral oncogene homolog (KR...,5x106 Cal-62 cells were seeded on a 100 mm pla...,The MaxQuant parameters were set as follows: e...,[],"[Targeted protein degradation, Protac, Kras, C...",,PARTIAL,...,Bottom-up proteomics,TMT,None,"[Homo sapiens (Human), thyroid gland]",Homo sapiens (human),None,[],"Vetma V, Puoti I, Karolak NK, Chakraborti S, D...",None,None
96,PXD065109,A sEH/COX-2 Dual Inhibitor PTUPB Reduces Endot...,None,Doxorubicin (DOX) is an effective anthracyclin...,Zebrafish studies were conducted in accordance...,The built-in search engine Andromeda in the Ma...,[],"[Soluble epoxide hydrolase, Zebrafish, Whole p...",,PARTIAL,...,"[Data-dependent acquisition, Bottom-up proteom...",[],None,"[Danio rerio (Zebrafish) (Brachydanio rerio), ...",Danio rerio (zebrafish) (brachydanio rerio),None,[],[],None,None
97,PXD065104,Quantitative proteomic analysis using 4D-FastD...,None,"In this study, we identified a significant lac...",Sample prepared（自己增加的样品准备步骤） Two established c...,The DIA data were processed using DIA-NN searc...,[],Proteomic analysis;4d-fastdia;gastric cancer; ...,,PARTIAL,...,Bottom-up proteomics,Relative quantification,None,"[cell culture, Homo sapiens (Human)]",Homo sapiens (human),None,[],[],None,None
98,PXD064940,Human HRI Autophosphorylation Profile,None,Heme-regulated inhibitorRegulated Inhibitor (H...,Lambda phosphatase treated HRI was produced as...,Data was processed using Mascot. Only peptides...,[],"[Autophosphorylation, Kinase, Hri]",10.6019/PXD064940,COMPLETE,...,Gel-based experiment,[],None,Homo sapiens (Human),Homo sapiens (human),None,[],"Kanta S, Vinciauskaite V, Neill G, Muqit M, Ma...",None,None
99,PXD064939,Autoimmunity-associated DIORA1 binds the MRCK ...,None,Genetic association links DIORA1 to numerous a...,Approximately 40 million SK-N-SH cells per sam...,Acquired raw data files were analyzed using Pr...,[],"[Autoimmunity, Fam167a, Epithelial-mesenchymal...",,PARTIAL,...,Bottom-up proteomics,TMT,None,"[cell culture, Homo sapiens (Human)]",Homo sapiens (human),None,[],[],None,None

In [ ]:
response, _ = instance.fetch_single(
    query={
        "projectAccession": "PXD066763",
    },
    method="projects",
    parse=True,
    format="dataframe",
)
response

,accession,title,additional_attributes,project_description,sample_processing_protocol,data_processing_protocol,project_tags,keywords,doi,submission_type,...,experiment_types,quantification_methods,countries,sample_attributes,organisms,organism_parts,diseases,references,identified_ptm_strings,total_file_downloads
0,PXD066763,Stereo-random Oligonucleotides Enable Efficien...,[],We used our previously published isASO-ID prot...,Proximity biotinylation experiment. Cells were...,MS spectra were processed with MaxQuant softwa...,[],"[Antisense oligonucleotide, Basu, Drug protein...",,PARTIAL,...,"{'@type': 'CvParam', 'cvLabel': 'PRIDE', 'acce...","{'@type': 'CvParam', 'cvLabel': 'PRIDE', 'acce...",Germany,"[{'@type': 'Tuple', 'key': {'cvLabel': 'EFO', ...","{'@type': 'CvParam', 'cvLabel': 'NEWT', 'acces...","{'@type': 'CvParam', 'cvLabel': 'CL', 'accessi...",[],[],"[{'@type': 'CvParam', 'cvLabel': 'MOD', 'acces...",17

In [ ]:
response, _ = instance.fetch_single(
    query={
        "accession": "PXD066763",
    },
    method="projects",
    option="similarProjects",
    parse=True,
    format="dataframe",
)
response

,accession,affiliations,avg_wonloads_per_file,data_processing_protocol,diseases,doi,download_count,experiment_types,instruments,keywords,...,sample_attributes,sample_processing_protocol,sdrf,softwares,submission_date,submission_type,submitters,title,updated_date,yearly_downloads
0,PXD045992,"Interfaculty Institute of Biochemistry, Univer...",8.633333,MS spectra were processed with MaxQuant softwa...,[],,777,Affinity purification coupled with mass spectr...,Q Exactive HF,"[Live cell, Bioid, Proximity biotinylation, Be...",...,"[Homo sapiens (Human), cervical cancer cell li...",Proximity biotinylation experiment. Hek293T Fl...,,MaxQuant,2023-10-09,PARTIAL,Mirita Franz-Wachtel,Profiling the interactome of oligonucleotide d...,2023-10-09,"[{'year': '2024', 'count': 95}, {'year': '2025..."
1,PXD013215,Interfaculty Institute of Biochemistry Univers...,47.230770,Spectra were processed with MaxQuant software ...,[],,614,[Affinity purification coupled with mass spect...,LTQ Orbitrap Elite,"[Budding yeast yer156c interactome, Chromatin,...",...,Saccharomyces cerevisiae (Baker's yeast),For SILAC APEX2 experiments the mitochondrial ...,,MaxQuant,2019-03-25,PARTIAL,Nicolas Nalpas,APEX2-mediated proximity labeling of mitochond...,2019-03-25,"[{'year': '2021', 'count': 84}, {'year': '2022..."
2,PXD011594,Center for Plant Molecular Biology (ZMBP) Univ...,40.600000,Spectra were processed with MaxQuant software ...,[],,203,Affinity purification coupled with mass spectr...,LTQ Orbitrap XL,"[Membrane traffic, Arf gtpases, Arabidopsis, A...",...,"[Arabidopsis thaliana (Mouse-ear cress), seedl...",Protein extracts from transgenic seedlings exp...,,MaxQuant,2018-11-07,PARTIAL,Nicolas Nalpas,Arabidopsis ARF-ARFGEF interaction analyzed by...,2018-11-07,"[{'year': '2021', 'count': 48}, {'year': '2022..."
3,PXD032366,Faculty of Biology & Biotechnology Ruhr-Univer...,6.894737,MS spectra were processed with MaxQuant softwa...,[],,131,Affinity purification coupled with mass spectr...,Q Exactive,"[Lc-msms, Bacterial effectors, Plants]",...,"[Nicotiana benthamiana, leaf]",Proteins were purified by SDS-PAGE (short run)...,,"[Andromeda, MaxQuant]",2022-03-17,PARTIAL,Mirita Franz-Wachtel,Characterization of Xanthomonas effector prote...,2022-03-17,"[{'year': '2023', 'count': 18}, {'year': '2024..."
4,PXD010694,University of Tuebingen - Interfaculty Institu...,41.400000,Acquired MS spectra were processed with MaxQua...,[],,414,Affinity purification coupled with mass spectr...,LTQ Orbitrap Elite,"[Rna localization, Bioid, Mouse, Rbps]",...,"[embryonic fibroblast, Mus musculus (Mouse)]","For RNA-BioID, cells were incubated with 50 µM...",,"[Andromeda, MaxQuant]",2018-08-06,PARTIAL,Mirita Franz-Wachtel,β-actin RNA-BioID,2018-08-06,"[{'year': '2021', 'count': 42}, {'year': '2022..."
5,PXD031610,"University of Tuebingen, Interfaculty Institut...",32.500000,MS spectra were processed with MaxQuant softwa...,[],,130,Affinity purification coupled with mass spectr...,Q Exactive,"[Mitochondria, Yeast, Signal-anchored proteins...",...,"[cell culture, Saccharomyces cerevisiae (Baker...",Pull-down assays were performed with extract o...,,"[Andromeda, MaxQuant]",2022-02-11,PARTIAL,Mirita Franz-Wachtel,Searching for the interaction partners in yeas...,2022-02-11,"[{'year': '2022', 'count': 12}, {'year': '2023..."
6,PXD045484,University of Halle-Wittenberg Institute for B...,19.923077,The MS data were processed with MaxQuant softw...,[],,259,Affinity purification coupled with mass spectr...,Q Exactive HF,[Comprehensive isolation by rna binding protei...,...,"[plant cell, Arabidopsis thaliana (Mouse-ear c...",LC-MS/MS analyses of eluted samples were perfo...,,MaxQuant,2023-09-19,PARTIAL,Irina Droste-Borel,Identification of U1 snRNA associated proteins,2023-09-19,"[{'year': '2024', 'count': 140}, {'year': '202..."
7,PXD033585,Faculty of Biology & Biotechnology Ruhr-Univer...,9.350000,MS spectra were processed with MaxQuant softwa...,[],,187,Affinity purification coupled with mass spectr...,Q Exactive,"[Lc-msms, Plants]",...,"[Nicotiana benthamiana, leaf]",: Proteins were purified by SDS-PAGE (short ru...,,"[Andromeda, MaxQuant]",2022-05-04,PARTIAL,Mirita Franz-Wachtel,Functional characterization of SH3P2 from Arab...,2022-05-04,"[{'year': '2022', 'count': 6}, {'year': '2023'..."
8,PXD005597,Junior Research Group Infection Biology of Sal...,9.214286,The MS data were processed with MaxQuant softw...,[],,258,Affinity purification coupled with mass spectr...,LTQ Orbitrap,"[T3ss, Flip, Flio, Export gate complex, Assembly]",...,Salmonella enterica subsp. enterica serovar Ty...,LC-MS/MS analyses were performed on an Easy na...,,MaxQuant,2016-12-20,PARTIAL,Nicolas Nalpas,FliP subcomplex analysis - A flagellum-specif...,2016-12-20,"[{'year': '2021', 'count': 52}, {'year': '2022..."
9,PXD036942,"University Tübingen, Center for Plant Molecula...",23.952381,Acquired MS spectra were processed with MaxQua...,[],,503,Affinity purification coupled with mass spectr...,Orbitrap Exploris 480,"[Pti, Arabidopsis, Cell death, Bir3, Plant imm...",...,"[Arabidopsis thaliana (Mouse-ear cress), leaf]",35S-BIR3-YFP expressing plants were used to im...,,"[Andromeda, MaxQuant]",2022-09-22,PARTIAL,Mirita Franz-Wachtel,Interactome of Arabidopsis BIR3 protein,2022-09-22,"[{'year': '2022', 'count': 6}, {'year': '2023'..."

## Pubchem

### Importing the API

In [1]:
from bioseq_dl import PubChemInterface

### Instantiating the API

In [2]:
instance = PubChemInterface()

### Making a request

In [3]:
response, _ = instance.fetch_single(
    query={"dictionary": "compound", "search_term": "C1=CC=C(C=C1)C=O"},
    method="autocomplete",
)
response

{'status': {'code': 0},
 'total': 10,
 'dictionary_terms': {'compound': ['1,3-oxazinan-2-one',
   '1,4-oxazepan-5-one',
   'Oxetan-3-one',
   '1-OCTEN-3-ONE',
   '2-oxa-6-azaspiro[3.4]octane',
   'Octan-2-one',
   '2-Oxa-6-azaspiro[3.4]octan-7-one',
   'Oxacyclohexadecan-2-one',
   '2-oxaspiro[3.5]nonan-7-one',
   '2-Azabicyclo[2.2.2]octan-3-one']}}

In [ ]:
response, _ = instance.fetch_batch(
    queries=[{"cid": "2244"}], method="pug_view/compound", parse=False, format="json"
)
response

[{'Record': {'RecordType': 'CID',
   'RecordNumber': 2244,
   'RecordTitle': 'Aspirin',
   'Section': [{'TOCHeading': 'Structures',
     'Description': 'Structure depictions of this compound, including computationally generated two-dimensional (2D) and three-dimensional (3D) structures, as well as experimentally determined 3D single-crystal structures.',
     'Section': [{'TOCHeading': '2D Structure',
       'Description': 'A two-dimensional (2D) structure representation of the compound.  Because this structure is processed through chemical structure standardization (Hähnke et al., J. Cheminform. 2018, 10, 36), it is not necessarily the same as the structures provided by individual data contributors.  ',
       'URL': 'https://doi.org/10.1186/s13321-018-0293-8',
       'DisplayControls': {'MoveToTop': True},
       'Information': [{'ReferenceNumber': 221,
         'Value': {'Boolean': [True]}}]},
      {'TOCHeading': '3D Conformer',
       'Description': 'A three-dimensional (3D) structure representation of the compound.  This 3D structure is not experimentally determined, but computed by PubChem.  This structure may or may not be the same as the inherent structure of the compound you would expect to see in vacuum or in the gas phase, because the underlying computational algorithm aims to generate a protein-bound structure, which would be observed in a protein-ligand complex.  More detailed information on this conformer model can be found in Kim et al., J. Cheminform. 2013, 5, 1.',
       'URL': 'https://doi.org/10.1186/1758-2946-5-1',
       'DisplayControls': {'MoveToTop': True},
       'Information': [{'ReferenceNumber': 221,
         'Description': 'Aspirin',
         'Value': {'Number': [2244]}}]},
      {'TOCHeading': 'Crystal Structures',
       'Description': 'This section provides links to crystallographic information from various sources.',
       'DisplayControls': {'CreateTable': {'FromInformationIn': 'Subsections',
         'NumberOfColumns': 2,
         'ColumnContents': ['Name', 'Value']},
        'MoveToTop': True,
        'ShowAtMost': 1},
       'Section': [{'TOCHeading': 'CCDC Number',
         'Description': 'A 6- or 7-digit-long numeric identifier assigned to the crystal structure in the Cambridge Crystallographic Data Centre (CCDC).',
         'URL': 'https://www.ccdc.cam.ac.uk',
         'Information': [{'ReferenceNumber': 181,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc66zzb',
           'Value': {'StringWithMarkup': [{'String': '185472'}]}},
          {'ReferenceNumber': 182,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6700f',
           'Value': {'StringWithMarkup': [{'String': '185473'}]}},
          {'ReferenceNumber': 183,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6701g',
           'Value': {'StringWithMarkup': [{'String': '185474'}]}},
          {'ReferenceNumber': 184,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6702h',
           'Value': {'StringWithMarkup': [{'String': '185475'}]}},
          {'ReferenceNumber': 185,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1md',
           'Value': {'StringWithMarkup': [{'String': '195133'}]}},
          {'ReferenceNumber': 186,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1nf',
           'Value': {'StringWithMarkup': [{'String': '195134'}]}},
          {'ReferenceNumber': 187,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1pg',
           'Value': {'StringWithMarkup': [{'String': '195135'}]}},
          {'ReferenceNumber': 188,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1qh',
           'Value': {'StringWithMarkup': [{'String': '195136'}]}},
          {'ReferenceNumber': 189,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1rj',
           'Value': {'StringWithMarkup': [{'String': '195137'}]}},
          {'ReferenceNumber': 190,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1sk',
           'Value': {'StringWithMarkup': [{'String': '195138'}]}},
          {'ReferenceNumber': 191,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc6k1tl',
           'Value': {'StringWithMarkup': [{'String': '195139'}]}},
          {'ReferenceNumber': 192,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cc9vfcx',
           'Value': {'StringWithMarkup': [{'String': '293519'}]}},
          {'ReferenceNumber': 193,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/ccnhr40',
           'Value': {'StringWithMarkup': [{'String': '610952'}]}},
          {'ReferenceNumber': 194,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/ccnqxbl',
           'Value': {'StringWithMarkup': [{'String': '617840'}]}},
          {'ReferenceNumber': 195,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/ccw6sqk',
           'Value': {'StringWithMarkup': [{'String': '810889'}]}},
          {'ReferenceNumber': 196,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/ccwk03j',
           'Value': {'StringWithMarkup': [{'String': '820697'}]}},
          {'ReferenceNumber': 197,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/ccwk04k',
           'Value': {'StringWithMarkup': [{'String': '820698'}]}},
          {'ReferenceNumber': 198,
           'Name': 'CCDC Number',
           'URL': 'http://doi.org/10.5517/cczc3dt',
           'Value': {'StringWithMarkup': [{'String': '904406'}]}}]},
        {'TOCHeading': 'COD Number',
         'Description': 'An identifier assigned to the crystal structure in the Crystallography Open Database (COD).',
         'URL': 'https://www.crystallography.net/cod',
         'DisplayControls': {'ListType': 'Columns'},
         'Information': [{'ReferenceNumber': 18,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/1515581.html',
           'Value': {'StringWithMarkup': [{'String': '1515581'}]}},
          {'ReferenceNumber': 19,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/1515582.html',
           'Value': {'StringWithMarkup': [{'String': '1515582'}]}},
          {'ReferenceNumber': 20,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/2104857.html',
           'Value': {'StringWithMarkup': [{'String': '2104857'}]}},
          {'ReferenceNumber': 21,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/4506597.html',
           'Value': {'StringWithMarkup': [{'String': '4506597'}]}},
          {'ReferenceNumber': 22,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/5000034.html',
           'Value': {'StringWithMarkup': [{'String': '5000034'}]}},
          {'ReferenceNumber': 23,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050897.html',
           'Value': {'StringWithMarkup': [{'String': '7050897'}]}},
          {'ReferenceNumber': 24,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050898.html',
           'Value': {'StringWithMarkup': [{'String': '7050898'}]}},
          {'ReferenceNumber': 25,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050899.html',
           'Value': {'StringWithMarkup': [{'String': '7050899'}]}},
          {'ReferenceNumber': 26,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050900.html',
           'Value': {'StringWithMarkup': [{'String': '7050900'}]}},
          {'ReferenceNumber': 27,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050901.html',
           'Value': {'StringWithMarkup': [{'String': '7050901'}]}},
          {'ReferenceNumber': 28,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050902.html',
           'Value': {'StringWithMarkup': [{'String': '7050902'}]}},
          {'ReferenceNumber': 29,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7050903.html',
           'Value': {'StringWithMarkup': [{'String': '7050903'}]}},
          {'ReferenceNumber': 30,
           'Name': 'COD Number',
           'URL': 'https://www.crystallography.net/cod/7126911.html',
           'Value': {'StringWithMarkup': [{'String': '7126911'}]}},
          {'ReferenceNumber': 31,
           'Name': 'COD records with this CID as component',
           'Value': {'StringWithMarkup': [{'String': '2009276',
              'Markup': [{'Start': 0,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/substance/?source=Crystallography+Open+Database&sourceid=2009276'}]}]}}]},
        {'TOCHeading': 'Associated Article',
         'Description': 'Publication associated with the crystal structure of the compound. Typically it is the paper in which the crystal structure was originally reported.',
         'Information': [{'ReferenceNumber': 18,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Varughese, Sunil; Kiran, M. S. R. N.; Solanko, Katarzyna A.; Bond, Andrew D.; Ramamurty, U.; Desiraju, Gautam R.. Interaction anisotropy and shear instability of aspirin polymorphs established by nanoindentation. Chemical Science 2011;2(11):2236-. DOI: 10.1039/c1sc00430a',
              'Markup': [{'Start': 253,
                'Length': 33,
                'URL': 'http://doi.org/10.1039/c1sc00430a'},
               {'Start': 162,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/aspirin',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'}]}]}},
          {'ReferenceNumber': 19,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Varughese, Sunil; Kiran, M. S. R. N.; Solanko, Katarzyna A.; Bond, Andrew D.; Ramamurty, U.; Desiraju, Gautam R.. Interaction anisotropy and shear instability of aspirin polymorphs established by nanoindentation. Chemical Science 2011;2(11):2236-. DOI: 10.1039/c1sc00430a',
              'Markup': [{'Start': 253,
                'Length': 33,
                'URL': 'http://doi.org/10.1039/c1sc00430a'},
               {'Start': 162,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/aspirin',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'}]}]}},
          {'ReferenceNumber': 20,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chan, E. J.; Welberry, T. R.; Heerdegen, A. P.; Goossens, D. J.. Diffuse scattering study of aspirin forms (I) and (II). Acta Crystallographica Section B 2010;66(6):696-707. DOI: 10.1107/S0108768110037055',
              'Markup': [{'Start': 179,
                'Length': 40,
                'URL': 'http://doi.org/10.1107/S0108768110037055'},
               {'Start': 93,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/aspirin',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'}]}]}},
          {'ReferenceNumber': 21,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Arputharaj, David Stephen; Hathwar, Venkatesha R.; Guru Row, Tayur N.; Kumaradhas, Poomani. Topological Electron Density Analysis and Electrostatic Properties of Aspirin: An Experimental and Theoretical Study. Crystal Growth & Design 2012;12(9):4357-. DOI: 10.1021/cg300269n',
              'Markup': [{'Start': 257,
                'Length': 32,
                'URL': 'http://doi.org/10.1021/cg300269n'},
               {'Start': 162,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/Aspirin',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'}]}]}},
          {'ReferenceNumber': 22,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Kim, Y.; Machida, K.; Taga, T.; Osaki, K.. Structure redetermination and packing analysis of aspirin crystal. Chemical & pharmaceutical bulletin 1985;33(7):2641-2647.',
              'Markup': [{'Start': 93,
                'Length': 7,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/aspirin',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'}]}]}},
          {'ReferenceNumber': 23,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 24,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 25,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 26,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 27,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 28,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',
                'Type': 'PubChem Internal Link',
                'Extra': 'Element-Hydrogen'}]}]}},
          {'ReferenceNumber': 29,
           'Name': 'Associated Article',
           'Value': {'StringWithMarkup': [{'String': 'Chick Wilson. Interesting proton behaviour in molecular structures. Variable temperature neutron diffraction and ab initio study of acetylsalicylic acid: characterising librational motions and comparing protons in different hydrogen bonding potentials. New Journal of Chemistry 2002;:-. DOI: 10.1039/b203775k',
              'Markup': [{'Start': 292,
                'Length': 31,
                'URL': 'http://doi.org/10.1039/b203775k'},
               {'Start': 132,
                'Length': 20,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/compound/acetylsalicylic%20acid',
                'Type': 'PubChem Internal Link',
                'Extra': 'CID-2244'},
               {'Start': 224,
                'Length': 8,
                'URL': 'https://pubchem.ncbi.nlm.nih.gov/element/Hydrogen',

For terms search you either can provide "word" or "complete" as name_type to match the term partially or completely.

In [ ]:
response, _ = instance.fetch_single(
    query={"name": "aspirin", "name_type": "word"}, method="pug/compound", parse=True, format="dataframe"
)
response

2025-12-10 16:35:33 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/aspirin/json?name_type=word

,cid,atoms_aids,atoms_elements,bonds_aid1,bonds_aid2,bonds_order,charge,props,count
0,2244,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, ...","[1, 1, 2, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, ...","[5, 12, 11, 21, 11, 12, 6, 7, 8, 11, 9, 14, 10...","[1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 13, 'atom_chiral': 0, 'atom_chi..."
1,1983,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 7, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, ...","[1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, ...","[9, 20, 10, 4, 10, 14, 5, 6, 7, 12, 8, 13, 9, ...","[1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 11, 'atom_chiral': 0, 'atom_chi..."
2,9871508,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 6, 6, ...","[1, 2, 3, 3, 4, 4, 5, 5, 6, 7, 8, 9, 9, 9, 10,...","[16, 17, 24, 37, 31, 61, 35, 65, 35, 34, 37, 1...","[2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 38, 'atom_chiral': 0, 'atom_chi..."
3,56842252,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, ...","[1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 9, 10, 10...","[23, 31, 29, 83, 35, 37, 42, 43, 47, 51, 52, 5...","[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 65, 'atom_chiral': 5, 'atom_chi..."
4,145904,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, ...","[1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 7, 8, 8, 9, 10,...","[20, 24, 34, 98, 32, 35, 49, 99, 49, 50, 100, ...","[1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 60, 'atom_chiral': 1, 'atom_chi..."
...,...,...,...,...,...,...,...,...,...
125,2820813,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[17, 8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1,...","[1, 2, 2, 3, 3, 4, 5, 6, 6, 6, 7, 8, 8, 9, 9, ...","[11, 7, 13, 12, 21, 12, 13, 7, 9, 12, 8, 10, 1...","[1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 14, 'atom_chiral': 0, 'atom_chi..."
126,150304,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, ...","[1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 8, 9, 10, 11...","[19, 20, 27, 47, 33, 75, 38, 79, 42, 82, 40, 4...","[2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 48, 'atom_chiral': 0, 'atom_chi..."
127,702,"[1, 2, 3, 4, 5, 6, 7, 8, 9]","[8, 6, 6, 1, 1, 1, 1, 1, 1]","[1, 1, 2, 2, 2, 3, 3, 3]","[2, 9, 3, 4, 5, 6, 7, 8]","[1, 1, 1, 1, 1, 1, 1, 1]",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 3, 'atom_chiral': 0, 'atom_chir..."
128,338,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1]","[1, 1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7, 7, 8, 8, 9]","[5, 15, 10, 16, 10, 5, 6, 10, 7, 8, 11, 9, 12,...","[1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1]",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 10, 'atom_chiral': 0, 'atom_chi..."
129,222,"[1, 2, 3, 4]","[7, 1, 1, 1]","[1, 1, 1]","[2, 3, 4]","[1, 1, 1]",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 1, 'atom_chiral': 0, 'atom_chir..."

In [ ]:
response, _ = instance.fetch_single(
    query={"name": "N-(4-hydroxyphenyl)acetamide"}, method="pug/compound", parse=True, format="dataframe"
)
response

,cid,atoms_aids,atoms_elements,bonds_aid1,bonds_aid2,bonds_order,charge,props,count
0,1983,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 7, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, ...","[1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, ...","[9, 20, 10, 4, 10, 14, 5, 6, 7, 12, 8, 13, 9, ...","[1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 11, 'atom_chiral': 0, 'atom_chi..."

In [ ]:
response, _ = instance.fetch_single(
    query={"name": "InChI=1S/C3H6O/c1-3(2)4/h1-2H3"}, method="pug/compound", parse=True, format="dataframe"
)
response

2025-12-10 22:59:45 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/InChI=1S/C3H6O/c1-3(2)4/h1-2H3/json?name_type=complete
2025-12-10 22:59:49 | ERROR    | bioseq_dl.interfaces.pubchem | Error fetching {'name': 'InChI=1S/C3H6O/c1-3(2)4/h1-2H3', 'name_type': 'complete'} for method 'pug/compound': 404 Client Error: PUGREST.NotFound for url: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/InChI=1S/C3H6O/c1-3(2)4/h1-2H3/json?name_type=complete

Empty DataFrame
Columns: []
Index: [0]

In [ ]:
response, _ = instance.fetch_single(
    query={
        "genesymbol": ["APP", "ECD"],
        "taxid": "9606",
    },
    method="pug/gene",
    option="summary",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:38:12 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/gene/genesymbol/APP,ECD/9606/summary/json

,gene_id,symbol,name,taxonomy_id,taxonomy,description,synonym
0,351,APP,amyloid beta precursor protein,9606,Homo sapiens (human),This gene encodes a cell surface receptor and ...,"[AAA, ABETA, ABPP, AD1, APPI, CTFgamma, CVAP, ..."
1,11319,ECD,ecdysoneless cell cycle regulator,9606,Homo sapiens (human),Enables histone acetyltransferase binding acti...,"[GCR2, HSGT1, SGT1, protein ecdysoneless homol..."
2,351,APP,amyloid beta precursor protein,9606,Homo sapiens (human),This gene encodes a cell surface receptor and ...,"[AAA, ABETA, ABPP, AD1, APPI, CTFgamma, CVAP, ..."
3,11319,ECD,ecdysoneless cell cycle regulator,9606,Homo sapiens (human),Enables histone acetyltransferase binding acti...,"[GCR2, HSGT1, SGT1, protein ecdysoneless homol..."

In [ ]:
# For more properties check the documentation: https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest#section=Compound-Property-Tables
response, _ = instance.fetch_single(
    query={
        "cid": ["2244", "2245"],
        # "name": "Adrenomedullin",
        # "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",
        # "property": ["molecularformula", "smiles", "hbonddonorcount", "hbondacceptorcount"],
        # "inchi": "InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)",
    },
    method="pug/compound",
    # option="sids",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:38:20 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244,2245/json

,cid,atoms_aids,atoms_elements,bonds_aid1,bonds_aid2,bonds_order,charge,props,count
0,2244,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, ...","[1, 1, 2, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, ...","[5, 12, 11, 21, 11, 12, 6, 7, 8, 11, 9, 14, 10...","[1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 13, 'atom_chiral': 0, 'atom_chi..."
1,2245,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[16, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 6, 6,...","[1, 1, 2, 3, 3, 4, 5, 6, 7, 7, 8, 9, 9, 9, 10,...","[14, 15, 18, 21, 46, 21, 22, 25, 32, 57, 33, 1...","[1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, ...",0,"[{'urn': {'label': 'Compound', 'name': 'Canoni...","{'heavy_atom': 34, 'atom_chiral': 5, 'atom_chi..."

In [ ]:
response, _ = instance.fetch_single(
    query={
        "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",
    },
    method="pug/compound",
    option="cids",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:39:00 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/CC(=O)OC1=CC=CC=C1C(=O)O/cids/json

    cid
0  2244

In [ ]:
response, _ = instance.fetch_single(
    query={
        "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",
    },
    method="pug/compound",
    option="description",
    parse=True,
    format="dataframe",
)
response

,cid,title,description,description_source_name,description_url
0,2244,Aspirin,None,None,None
1,2244,None,Aspirin can cause developmental toxicity and f...,California Office of Environmental Health Haza...,https://oehha.ca.gov/proposition-65/chemicals/...
2,2244,None,Acetylsalicylic acid is a member of the class ...,ChEBI,https://www.ebi.ac.uk/chebi/searchId.do?chebiI...

In [ ]:
response, _ = instance.fetch_single(
    query={
        "accession": "P00533",
    },
    method="pug/protein",
    option="summary",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:39:39 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/protein/accession/P00533/summary/json

,protein_accession,name,taxonomy_id,taxonomy,synonym
0,P00533,Epidermal growth factor receptor,9606,Homo sapiens (human),"[EC 2.7.10.1, Proto-oncogene c-ErbB-1, Recepto..."

In [ ]:
response, _ = instance.fetch_single(
    query={
        "accession": "P00533",
    },
    method="pug/protein",
    option="aids",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:39:48 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/protein/accession/P00533/aids/json

  protein_accession                                                aid
0            P00533  [1433, 1726, 1727, 1729, 1731, 1742, 1982, 336...

In [ ]:
response, _ = instance.fetch_single(
    query={
        "accession": "P00533",
    },
    method="pug/protein",
    option="concise",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:40:01 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/protein/accession/P00533/concise/json

,aid,sid,cid,activity_outcome,target_accession,target_geneid,activity_name,activity_qualifier,activity_value_um,assay_name,assay_type,pubmed_id,rna_i
0,3364,103262069,5329249,Active,None,,IC50,=,4.32,Inhibition of ligand-induced proliferation in ...,Confirmatory,12127526,None
1,3364,103262170,10300451,Active,None,,IC50,=,0.62,Inhibition of ligand-induced proliferation in ...,Confirmatory,12127526,None
2,3364,103262784,5329232,Active,None,,IC50,=,7.82,Inhibition of ligand-induced proliferation in ...,Confirmatory,12127526,None
3,3364,103262821,5329244,Active,None,,IC50,=,1.29,Inhibition of ligand-induced proliferation in ...,Confirmatory,12127526,None
4,3364,103262822,5329243,Active,None,,IC50,=,7.5,Inhibition of ligand-induced proliferation in ...,Confirmatory,12127526,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49266,2199767,242651810,46220502,Unspecified,None,,,,,Inhibition of MIB binding to EGFR in human NCI...,Other,29133594,None
49267,2199990,242651810,46220502,Unspecified,None,,,,,Inhibition of MIB binding to EGFR in human NCI...,Other,29133594,None
49268,2200097,242651810,46220502,Unspecified,None,,,,,Inhibition of MIB binding to EGFR in human NCI...,Other,29133594,None
49269,2201454,520046609,165404856,Unspecified,None,,,,,activity of EGFR(h) at 1.0 µM in the Eurofins ...,Other,,None
49270,2201794,494404043,42602622,Inactive,None,,,,,Activity against EGF/HU in the Eurofins Safet...,Other,,None

In [ ]:
response, _ = instance.fetch_single(
    query={
        "accession": "P00533",
    },
    method="pug/protein",
    option="pwaccs",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:40:45 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/protein/accession/P00533/pwaccs/json

  protein_accession                                  pathway_accession
0            P00533  [PathBank:SMP0000472, PathBank:SMP0000473, Pat...

In [ ]:
response, _ = instance.fetch_single(
    query={"genesymbol": ["APP"]}, method="pug/gene", option="summary", parse=True, format="dataframe"
)
response

,gene_id,symbol,name,taxonomy_id,taxonomy,description,synonym
0,351,APP,amyloid beta precursor protein,9606,Homo sapiens (human),This gene encodes a cell surface receptor and ...,"[AAA, ABETA, ABPP, AD1, APPI, CTFgamma, CVAP, ..."

In [ ]:
response, _ = instance.fetch_single(
    query={
        "genesymbol": ["APP", "ECD"],
    },
    method="pug/gene",
    option="summary",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:41:16 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/gene/genesymbol/ECD/summary/json

,gene_id,symbol,name,taxonomy_id,taxonomy,description,synonym
0,351,APP,amyloid beta precursor protein,9606,Homo sapiens (human),This gene encodes a cell surface receptor and ...,"[AAA, ABETA, ABPP, AD1, APPI, CTFgamma, CVAP, ..."
1,11319,ECD,ecdysoneless cell cycle regulator,9606,Homo sapiens (human),Enables histone acetyltransferase binding acti...,"[GCR2, HSGT1, SGT1, protein ecdysoneless homol..."

In [ ]:
response, _ = instance.fetch_single(
    query={
        "genesymbol": ["APP"],
    },
    method="pug/gene",
    option="concise",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:41:26 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/gene/genesymbol/APP/concise/json

,aid,sid,cid,activity_outcome,target_accession,target_geneid,activity_name,activity_qualifier,activity_value_um,assay_name,assay_type,pubmed_id,rna_i
0,253457,103446574,11351105,Active,P05067,None,EC50,=,0.64,In vitro elevation of beta C-terminal fragment...,Confirmatory,15780628,
1,369040,103630879,827500,Active,P05067,None,,,,Binding affinity to human APP expressed in tra...,Other,19147351,
2,374280,103655343,42603729,Active,P05067,None,,,,Binding affinity to core beta-amyloid plaques ...,Other,18992967,
3,374281,103655343,42603729,Active,P05067,None,,,,Binding affinity to vascular beta-amyloid plaq...,Other,18992967,
4,452720,103700447,11543843,Unspecified,P05067,None,EC50,=,16,Inhibition of human recombinant APP expressed ...,Confirmatory,19959359,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1805804,459630156,90352662,Active,P05067,None,Kd,,0.3,"BiaCore assay from US Patent US11091444: ""Hyda...",Confirmatory,,
136,1805804,459630159,77106312,Active,P05067,None,IC50,,0.15,"BiaCore assay from US Patent US11091444: ""Hyda...",Confirmatory,,
137,1515584,103218648,656629,Active,P05067,None,IC50,=,0.19953,Inhibition of APP (unknown origin),Confirmatory,30655952,
138,1805804,442137664,146223006,Inactive,P05067,None,Kd,>,50,"BiaCore assay from US Patent US11091444: ""Hyda...",Confirmatory,,
139,1805804,459630159,77106312,Active,P05067,None,Kd,<,1,"BiaCore assay from US Patent US11091444: ""Hyda...",Confirmatory,,

In [ ]:
response, _ = instance.fetch_single(
    query={
        "genesymbol": ["APP"],
    },
    method="pug/gene",
    option="pwaccs",
    parse=True,
    format="dataframe",
)
response

2025-11-28 13:42:18 | INFO     | bioseq_dl.interfaces.pubchem | Prepared request: https://pubchem.ncbi.nlm.nih.gov/rest/pug/gene/genesymbol/APP/pwaccs/json

Empty DataFrame
Columns: []
Index: []

## Reactome

### Importing the API

In [39]:
from bioseq_dl import ReactomeInterface

### Instantiating the API

In [40]:
instance = ReactomeInterface()

### Making a Request

In [ ]:
response, _ = instance.fetch_single(
    query="R-DME-1834941", parse=True, method="data-discover", format="dataframe"
)
response

,name,description,url,version,keywords,includedInDataCatalog,distribution,license,@context,@type
0,STING mediated induction of host immune responses,This event has been computationally inferred f...,https://reactome.org/PathwayBrowser/#/R-DME-18...,94,[Pathway],"{'name': 'Reactome', 'url': 'https://reactome....",[{'contentUrl': 'https://reactome.org/ContentS...,https://creativecommons.org/licenses/by/4.0/,http://schema.org/,DataSet

## RHEA

### Importing the API

In [42]:
from bioseq_dl import RheaInterface

### Instantiating the API

In [43]:
instance = RheaInterface()

### Making a Request

In [ ]:
response, _ = instance.fetch_single(
    query={"query": "uniprot:*"}, method="rhea", parse=True, format="dataframe"
)
response

,id,equation,status,htmlequation,comment,balanced,transport
0,21252,(S)-2-hydroxyglutarate + A = 2-oxoglutarate + AH2,approved,"<span class=""participant""><span class=""stoichi...",,True,False
1,21256,3-phosphoshikimate + phosphoenolpyruvate = 5-O...,approved,"<span class=""participant""><span class=""stoichi...",,True,False
2,21260,[thioredoxin]-disulfide + L-methionine + H2O =...,approved,"<span class=""participant""><span class=""stoichi...",,True,False
3,21264,glycolate + A = glyoxylate + AH2,approved,"<span class=""participant""><span class=""stoichi...",,True,False
4,21272,spermidine + glutathione + ATP = glutathionyls...,approved,"<span class=""participant""><span class=""stoichi...",,True,False
...,...,...,...,...,...,...,...
95,21800,all-trans-antheraxanthin + L-ascorbate = all-t...,approved,"<span class=""participant""><span class=""stoichi...",RHEA:21800 part of RHEA:32371 \n\nPublished in...,True,False
96,21804,myo-inositol + ATP = 1D-myo-inositol 3-phospha...,approved,"<span class=""participant""><span class=""stoichi...",,True,False
97,21812,cholesterol + reduced [NADPH--hemoprotein redu...,approved,"<span class=""participant""><span class=""stoichi...",,True,False
98,21816,a D-alpha-amino acid + O2 + H2O = a 2-oxocarbo...,approved,"<span class=""participant""><span class=""stoichi...",Multi-step reaction: RHEA:78799 + RHEA:78803,True,False
99,21824,L-aspartate + 2-oxoglutarate = oxaloacetate + ...,approved,"<span class=""participant""><span class=""stoichi...",,True,False

## Refseq

### Importing the API

In [45]:
from bioseq_dl import RefSeqInterface

### Instantiating the API

In [46]:
instance = RefSeqInterface()

### Making a Request

In [ ]:
response, _ = instance.fetch_single(
    query=["XP_010804480.1", "XP_010804481.1", "XP_010804482.1"],
    method="protein",
    parse=True,
    format="dataframe",
)
response

/home/diego/micromamba/envs/bioseqdownloader/lib/python3.13/site-packages/Bio/Entrez/__init__.py:734: UserWarning:
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(

          locus  project_id
0  XP_010804480  PRJNA33843
1  XP_010804481  PRJNA33843
2  XP_010804482  PRJNA33843

In [ ]:
response, _ = instance.fetch_batch(
    queries=["XP_010804480.1", "XP_010804481.1", "XP_010804482.1"],
    method="protein",
    parse=True,
    format="dataframe",
)
response

/home/diego/micromamba/envs/bioseqdownloader/lib/python3.13/site-packages/Bio/Entrez/__init__.py:734: UserWarning:
            Email address is not specified.

            To make use of NCBI's E-utilities, NCBI requires you to specify your
            email address with each request.  As an example, if your email address
            is A.N.Other@example.com, you can specify it as follows:
               from Bio import Entrez
               Entrez.email = 'A.N.Other@example.com'
            In case of excessive usage of the E-utilities, NCBI will attempt to contact
            a user at the email address provided before blocking access to the
            E-utilities.
  warnings.warn(

          locus  project_id
0  XP_010804480  PRJNA33843
1  XP_010804481  PRJNA33843
2  XP_010804482  PRJNA33843

## SabioRK

### Importing the API

In [13]:
from bioseq_dl import SabiorkInterface

### Instantiating the API

In [14]:
instance = SabiorkInterface()

### Making a Request

In [15]:
response, metadata = instance.fetch_single(
    query={"UniProtKB_AC": "Q96DT6"}, method="kineticlaws", parse=True, format="dataframe"
)
response

,EntryID,Organism,UniprotID,ECNumber,parameter.name,parameter.type,parameter.associatedSpecies,parameter.startValue,parameter.endValue,parameter.standardDeviation,parameter.unit,Reaction,Temperature,pH,Tissue
0,72930,Homo sapiens,Q96DT6 Q9GZQ8,3.4.22,kcat_Km,kcat/Km,LC3B-GST,12.2,,-,M^(-1)*s^(-1),H2O + LC3B-GST = LC3B + GST,37.0,7.2,HEK-293A cell
1,72930,Homo sapiens,Q96DT6 Q9GZQ8,3.4.22,Km,Km,LC3B-GST,4.75E-5,,2.4E-6,M,H2O + LC3B-GST = LC3B + GST,37.0,7.2,HEK-293A cell
2,72930,Homo sapiens,Q96DT6 Q9GZQ8,3.4.22,S,concentration,LC3B-GST,0.0,2.0E-5,-,M,H2O + LC3B-GST = LC3B + GST,37.0,7.2,HEK-293A cell
3,72936,Homo sapiens,P60520 Q96DT6,3.4.22,kcat_Km,kcat/Km,GATE16-GST,20.3,,-,M^(-1)*s^(-1),H2O + GATE16-GST = GST + GATE16,37.0,7.2,HEK-293A cell
4,72936,Homo sapiens,P60520 Q96DT6,3.4.22,S,concentration,GATE16-GST,0.0,2.0E-5,-,M,H2O + GATE16-GST = GST + GATE16,37.0,7.2,HEK-293A cell
5,72936,Homo sapiens,P60520 Q96DT6,3.4.22,Km,Km,GATE16-GST,1.24E-5,,1.3E-6,M,H2O + GATE16-GST = GST + GATE16,37.0,7.2,HEK-293A cell

## STRING

### Importing the API

In [50]:
from bioseq_dl import StringInterface

### Instantiating the API

In [51]:
instance = StringInterface()

### Making a Request

In [ ]:
response, _ = instance.fetch_single(
    query={
        "identifiers": ["p53"],
    },
    method="get_string_ids",
    parse=True,
    format="dataframe",
)
response

   query_index query_item                str_id
0            0        p53  9606.ENSP00000269305

In [ ]:
response, _ = instance.fetch_single(
    method="interaction_partners",
    query={
        "identifiers": ["p53", "cdk2"],
        "species": 9606,
    },
    parse=True,
    format="dataframe",
)
response

,id_a,id_b,name_a,name_b,score,nscore,fscore,pscore,ascore,escore,dscore,tscore
0,9606.ENSP00000266970,9606.ENSP00000481380,CDK2,CCNA2,0.999,0,0.003,0.0,0.453,0.999,0.9,0.999
1,9606.ENSP00000266970,9606.ENSP00000413720,CDK2,CDKN1C,0.999,0,0.000,0.0,0.085,0.859,0.9,0.970
2,9606.ENSP00000266970,9606.ENSP00000228872,CDK2,CDKN1B,0.999,0,0.000,0.0,0.085,0.999,0.9,0.999
3,9606.ENSP00000266970,9606.ENSP00000429089,CDK2,CCNE2,0.999,0,0.000,0.0,0.200,0.995,0.9,0.996
4,9606.ENSP00000266970,9606.ENSP00000255465,CDK2,CCNA1,0.999,0,0.000,0.0,0.292,0.942,0.9,0.999
...,...,...,...,...,...,...,...,...,...,...,...,...
5917,9606.ENSP00000269305,9606.ENSP00000310928,TP53,PPARD,0.400,0,0.000,0.0,0.000,0.000,0.0,0.400
5918,9606.ENSP00000269305,9606.ENSP00000419945,TP53,ERVW-1,0.400,0,0.000,0.0,0.000,0.000,0.0,0.400
5919,9606.ENSP00000269305,9606.ENSP00000462980,TP53,TAF4B,0.400,0,0.000,0.0,0.000,0.000,0.4,0.000
5920,9606.ENSP00000269305,9606.ENSP00000431885,TP53,TYK2,0.400,0,0.000,0.0,0.083,0.000,0.0,0.372
5921,9606.ENSP00000269305,9606.ENSP00000356247,TP53,LGR6,0.400,0,0.000,0.0,0.000,0.165,0.0,0.311

In [ ]:
response, _ = instance.fetch_batch(
    outfmt="json",
    method="interaction_partners",
    queries=[
        {
            "identifiers": ["p53", "cdk2"],
            "species": 9606,
        }
    ],
    parse=True,
    format="dataframe",
)
response

,id_a,id_b,name_a,name_b,score,nscore,fscore,pscore,ascore,escore,dscore,tscore
0,9606.ENSP00000266970,9606.ENSP00000481380,CDK2,CCNA2,0.999,0,0.003,0.0,0.453,0.999,0.9,0.999
1,9606.ENSP00000266970,9606.ENSP00000413720,CDK2,CDKN1C,0.999,0,0.000,0.0,0.085,0.859,0.9,0.970
2,9606.ENSP00000266970,9606.ENSP00000228872,CDK2,CDKN1B,0.999,0,0.000,0.0,0.085,0.999,0.9,0.999
3,9606.ENSP00000266970,9606.ENSP00000429089,CDK2,CCNE2,0.999,0,0.000,0.0,0.200,0.995,0.9,0.996
4,9606.ENSP00000266970,9606.ENSP00000255465,CDK2,CCNA1,0.999,0,0.000,0.0,0.292,0.942,0.9,0.999
...,...,...,...,...,...,...,...,...,...,...,...,...
5917,9606.ENSP00000269305,9606.ENSP00000310928,TP53,PPARD,0.400,0,0.000,0.0,0.000,0.000,0.0,0.400
5918,9606.ENSP00000269305,9606.ENSP00000419945,TP53,ERVW-1,0.400,0,0.000,0.0,0.000,0.000,0.0,0.400
5919,9606.ENSP00000269305,9606.ENSP00000462980,TP53,TAF4B,0.400,0,0.000,0.0,0.000,0.000,0.4,0.000
5920,9606.ENSP00000269305,9606.ENSP00000431885,TP53,TYK2,0.400,0,0.000,0.0,0.083,0.000,0.0,0.372
5921,9606.ENSP00000269305,9606.ENSP00000356247,TP53,LGR6,0.400,0,0.000,0.0,0.000,0.165,0.0,0.311